# 09 - Searching New Dataset / Badataset

Bu notebook iki isi yapar:

1. Projede halihazirda kullanilan veri setlerini ve neden kullanildiklarini ozetler.
2. Teze eklenebilecek/ek degerlendirme icin dusunulebilecek veri setlerini karsilastirir ve her biri icin 5'er ornek kayit uretir.

Arastirma ve guncelleme tarihi: 2026-08-03

Not: `SEntFiN`, `FiQA` ve `FinEntity` projede target-level veri seti icinde zaten kullanilmis gorunuyor. Bu yuzden dis test olarak kullanilacaklarsa ayni satirlarla degil, egitimden ayrilmis holdout veya yeni orneklerle kullanilmalari gerekir.

In [1]:
import sys
from pathlib import Path

ROOT = Path.cwd().resolve()
APP_DIR_CANDIDATES = [ROOT / "app", ROOT]
for app_dir_candidate in APP_DIR_CANDIDATES:
    if (app_dir_candidate / "thesis_utils").exists() and str(app_dir_candidate) not in sys.path:
        sys.path.insert(0, str(app_dir_candidate))

import pandas as pd
from IPython.display import Markdown, display
from thesis_utils.paths import PROJECT_ROOT, DATA_ROOT, ensure_data_directories

ensure_data_directories()
EXTERNAL_CANDIDATE_DIR = DATA_ROOT / "external_candidates"
EXTERNAL_CANDIDATE_DIR.mkdir(parents=True, exist_ok=True)

print("Project root:", PROJECT_ROOT)
print("External candidate dir:", EXTERNAL_CANDIDATE_DIR)

Project root: D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis
External candidate dir: D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\external_candidates

## 1. Projede kullanilan veri setleri ve nedenleri

Asagidaki tablo yerel dosyalardan ve mevcut training/evaluation yapilandirmasindan cikarildi. Amac, her veri setinin tezde hangi boslugu doldurdugunu acikca gostermektir.

In [2]:
used_path = EXTERNAL_CANDIDATE_DIR / "project_used_dataset_rationale.csv"
used_dataset_rationale = pd.read_csv(used_path)
display(used_dataset_rationale)

,dataset,dataset_full_name,where_used,rows_in_project,why_used,risk_note
0,FinancialPhraseBank,Financial PhraseBank,auxiliary train only,4846.0,Finans haber cumlelerinde insan etiketli klasi...,FinBERT egitim/asinalik riski nedeniyle yalniz...
1,TwitterFinancialNewsSentiment,Twitter Financial News Sentiment,plain sentiment train/validation/test,11931.0,"Finansal tweet/kisa metinleri bearish, neutral...",Sinif dagilimi neutral agirlikli; macro-F1 bu ...
2,FiQA,FiQA 2018 Sentiment Classification,target/entity-level sentiment dataset,1173.0,Aspect/target ve -1 ile +1 arasi skor icerdigi...,Ayni ornekler egitimde kullanildiysa bagimsiz ...
3,FinEntity,FinEntity,target/entity-level sentiment dataset,979.0,Finansal metinlerde entity span ve positive/ne...,Ayni ornekler egitimde kullanildiysa bagimsiz ...
4,SEntFiN,SEntFiN 1.0,target/entity-level sentiment dataset,14371.0,Finans haber basliklarinda entity bazli insan ...,Ayni ornekler egitimde kullanildiysa bagimsiz ...
5,SP500 headlines 2008-2024,S&P 500 financial news headlines,"raw source, FinBERT pseudo-labeling, SP500 hum...",19127.0,Piyasa yonu ve S&P 500 odakli haber basliklari...,Projede zaten kullanildigi icin yeni dis test ...
6,Reuters news,Reuters financial/news headlines from aggregat...,Reuters 5000 human annotation external-style e...,6433.0,SP500 disindaki haber akisindan 5000 ornek sec...,Baslik cikarma ve finansal ilgililik filtresi ...
7,Aggregated financial news enriched,Merged/enriched financial news pool,"source pool, filtering, pseudo-labeling and an...",943326.0,"Reuters, daily stock news, crypto news ve bitc...",Kaynaklar ayni guvenilirlikte degildir; gold t...
8,Synthetic financial news,Synthetic financial news evaluation batches,synthetic robustness evaluation,NaN,Negative/neutral/positive siniflarinda kontrol...,Sentetik oldugu icin gercek dagilim performans...

## 2. Mevcut veri setlerinden 5'er ornek

Bu ornekler hocaya veri tipini gostermek icin sadelestirilmis alanlarla kaydedildi. Tam tablolar `db` altinda duruyor.

In [3]:
used_examples_path = EXTERNAL_CANDIDATE_DIR / "project_used_dataset_examples.csv"
used_dataset_examples = pd.read_csv(used_examples_path)
for dataset_name, part in used_dataset_examples.groupby("dataset", sort=False):
    display(Markdown(f"### {dataset_name}"))
    display(part.head(5))

### TwitterFinancialNewsSentiment

,dataset,sample_id,text,label,source_dataset,target,entity,aspect,Date,Title,annotation_id,date,final_label,finbert_label,finbert_confidence,text_en
0,TwitterFinancialNewsSentiment,PLAIN_SENT_0000001,$BYND - JPMorgan reels in expectations on Beyo...,negative,TwitterFinancialNewsSentiment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,TwitterFinancialNewsSentiment,PLAIN_SENT_0000002,$CCL $RCL - Nomura points to bookings weakness...,negative,TwitterFinancialNewsSentiment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,TwitterFinancialNewsSentiment,PLAIN_SENT_0000003,"$CX - Cemex cut at Credit Suisse, J.P. Morgan ...",negative,TwitterFinancialNewsSentiment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,TwitterFinancialNewsSentiment,PLAIN_SENT_0000004,$ESS: BTIG Research cuts to Neutral https://t....,negative,TwitterFinancialNewsSentiment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,TwitterFinancialNewsSentiment,PLAIN_SENT_0000005,$FNKO - Funko slides after Piper Jaffray PT cu...,negative,TwitterFinancialNewsSentiment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### FinancialPhraseBank

,dataset,sample_id,text,label,source_dataset,target,entity,aspect,Date,Title,annotation_id,date,final_label,finbert_label,finbert_confidence,text_en
5,FinancialPhraseBank,PLAIN_SENT_0011932,EBIT margin was up from 1.4 % to 5.1 % .,positive,FinancialPhraseBank,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6,FinancialPhraseBank,PLAIN_SENT_0011933,The current lay-offs are additional to the tem...,negative,FinancialPhraseBank,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
7,FinancialPhraseBank,PLAIN_SENT_0011934,The acquisition is expected to take place by t...,neutral,FinancialPhraseBank,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
8,FinancialPhraseBank,PLAIN_SENT_0011935,Strong brand visibility nationally and regiona...,neutral,FinancialPhraseBank,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
9,FinancialPhraseBank,PLAIN_SENT_0011936,The end-to-end delivery combines the competenc...,neutral,FinancialPhraseBank,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### SEntFiN

,dataset,sample_id,text,label,source_dataset,target,entity,aspect,Date,Title,annotation_id,date,final_label,finbert_label,finbert_confidence,text_en
10,SEntFiN,TGT_SENT_0000001,SpiceJet to issue 6.4 crore warrants to promoters,neutral,SEntFiN,SpiceJet,SpiceJet,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
11,SEntFiN,TGT_SENT_0000002,MMTC Q2 net loss at Rs 10.4 crore,neutral,SEntFiN,MMTC,MMTC,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
12,SEntFiN,TGT_SENT_0000003,"Mid-cap funds can deliver more, stay put: Experts",positive,SEntFiN,Mid-cap funds,Mid-cap funds,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
13,SEntFiN,TGT_SENT_0000004,Mid caps now turn into market darlings,positive,SEntFiN,Mid caps,Mid caps,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
14,SEntFiN,TGT_SENT_0000005,"Market seeing patience, if not conviction: Pra...",neutral,SEntFiN,Market,Market,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### FiQA

,dataset,sample_id,text,label,source_dataset,target,entity,aspect,Date,Title,annotation_id,date,final_label,finbert_label,finbert_confidence,text_en
15,FiQA,TGT_SENT_0014372,Royal Mail chairman Donald Brydon set to step ...,negative,FiQA,Royal Mail,Royal Mail,Corporate/Appointment,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
16,FiQA,TGT_SENT_0014373,Slump in Weir leads FTSE down from record high,negative,FiQA,Weir,Weir,Market/Volatility/Volatility,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
17,FiQA,TGT_SENT_0014374,AstraZeneca wins FDA approval for key new lung...,positive,FiQA,AstraZeneca,AstraZeneca,Corporate/Regulatory,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
18,FiQA,TGT_SENT_0014375,UPDATE 1-Lloyds to cut 945 jobs as part of 3-y...,negative,FiQA,Lloyds,Lloyds,Corporate/Strategy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
19,FiQA,TGT_SENT_0014376,Standard Chartered Shifts Emerging-Markets Str...,negative,FiQA,Standard Chartered,Standard Chartered,Corporate/Strategy,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### FinEntity

,dataset,sample_id,text,label,source_dataset,target,entity,aspect,Date,Title,annotation_id,date,final_label,finbert_label,finbert_confidence,text_en
20,FinEntity,TGT_SENT_0015545,Johnson & Johnson <JNJ.N> shares gained 0.20% ...,NaN,FinEntity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
21,FinEntity,TGT_SENT_0015546,"On the positive side, Siemens is rallying 6% a...",NaN,FinEntity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
22,FinEntity,TGT_SENT_0015547,Brent crude <LCOc1> rose 1.4% to $100.69 per b...,NaN,FinEntity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
23,FinEntity,TGT_SENT_0015548,"Nearly all major S&P 500 sectors are red, with...",NaN,FinEntity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
24,FinEntity,TGT_SENT_0015549,NEW YORK - Wall Street ended sharply higher on...,NaN,FinEntity,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### SP500 headlines 2008-2024

,dataset,sample_id,text,label,source_dataset,target,entity,aspect,Date,Title,annotation_id,date,final_label,finbert_label,finbert_confidence,text_en
25,SP500 headlines 2008-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-01-02,"JPMorgan Predicts 2008 Will Be ""Nothing But Net""",NaN,NaN,NaN,NaN,NaN,NaN
26,SP500 headlines 2008-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-01-02,Dow Tallies Biggest First-session-of-year Poin...,NaN,NaN,NaN,NaN,NaN,NaN
27,SP500 headlines 2008-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-01-02,2008 predictions for the S&P 500,NaN,NaN,NaN,NaN,NaN,NaN
28,SP500 headlines 2008-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-01-03,"U.S. Stocks Higher After Economic Data, Monsan...",NaN,NaN,NaN,NaN,NaN,NaN
29,SP500 headlines 2008-2024,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2008-01-07,U.S. Stocks Climb As Hopes Increase For More F...,NaN,NaN,NaN,NaN,NaN,NaN

### SP500 human annotation master

,dataset,sample_id,text,label,source_dataset,target,entity,aspect,Date,Title,annotation_id,date,final_label,finbert_label,finbert_confidence,text_en
30,SP500 human annotation master,SP500_HEAD_000004,"U.S. Stocks Higher After Economic Data, Monsan...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,SP500_ANN_0001,2008-01-03,NaN,positive,0.861627,NaN
31,SP500 human annotation master,SP500_HEAD_016918,Stock Market Outlook 2024: Rare Bullish Signal...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SP500_ANN_0002,2023-12-15,NaN,positive,0.881073,NaN
32,SP500 human annotation master,SP500_HEAD_013289,Federal Reserve Rate Hike Odds Grow As Bank-Cr...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SP500_ANN_0003,2023-03-20,NaN,negative,0.625434,NaN
33,SP500 human annotation master,SP500_HEAD_017167,"US Stock Market Closing: Dow Jones, S&P 500 Re...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,SP500_ANN_0004,2024-01-04,NaN,negative,0.949325,NaN
34,SP500 human annotation master,SP500_HEAD_007040,"Deutsche Bank: S&P 500 13% Overvalued, Recessi...",NaN,NaN,NaN,NaN,NaN,NaN,NaN,SP500_ANN_0005,2019-09-18,NaN,negative,0.947802,NaN

### Reuters human annotation master

,dataset,sample_id,text,label,source_dataset,target,entity,aspect,Date,Title,annotation_id,date,final_label,finbert_label,finbert_confidence,text_en
35,Reuters human annotation master,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REUTERS_ANN_00001,2007-04-12,negative,negative,0.683211,s.africa watchdog to probe gold fields bid report
36,Reuters human annotation master,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REUTERS_ANN_00002,2007-04-26,positive,neutral,0.847032,new barbie girls sashay into view with mp-3
37,Reuters human annotation master,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REUTERS_ANN_00003,2006-12-17,neutral,neutral,0.865116,"stocks await data, mergers and santa"
38,Reuters human annotation master,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REUTERS_ANN_00004,2007-01-03,negative,negative,0.960498,canadian dollar falls to 9-mth lows vs u.s. do...
39,Reuters human annotation master,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,REUTERS_ANN_00005,2007-02-05,negative,negative,0.964671,"techs buckle under microsoft, wal-mart helps dow"

## 3. Eklenebilecek veri setleri

Burada adaylar iki gruptur: gercekten yeni eklenebilecek havuzlar ve projede zaten bulunup ancak ayri holdout/evaluation tasarimiyla kullanilabilecek kaynaklar. Siralama, tez katkisi ve bagimsizlik acisindan yapilmistir.

In [4]:
addable_path = EXTERNAL_CANDIDATE_DIR / "addable_dataset_research_matrix.csv"
addable_dataset_matrix = pd.read_csv(addable_path)
display(addable_dataset_matrix)

,rank,name,source_url,status_for_project,size_note,why_add,main_caveat
0,1,NOSIBLE Financial Sentiment,https://huggingface.co/datasets/NOSIBLE/financ...,new_manual_annotation_pool,"100,000 examples on Hugging Face",Guncel ve farkli domainlerden haber/snippet ha...,Etiketler LLM/aktif ogrenme pipeline kaynaklid...
1,2,SENTiVENT Bench,https://huggingface.co/datasets/GillesJacobs/s...,new_advanced_event_level_eval,expert event and implicit sentiment annotations,"Yalnizca uc sinifli metin etiketi degil, event...",Mevcut negative/neutral/positive semasina donu...
2,3,FNSPID,https://huggingface.co/datasets/Zihan1004/FNSPID,new_news_price_time_series_pool,15.7M financial news records and 29.7M stock p...,Haber basliklarini hisse sembolu ve zaman bilg...,"Cok buyuk veri; ornekleme, kaynak temizligi ve..."
3,4,SEntFiN 1.0 / v1.1,https://www.kaggle.com/datasets/ankurzing/aspe...,already_in_target_dataset_holdout_only,"10,753 headlines; 2,847 multi-entity headlines...",Entity-aware finans haber basligi yapisi tezin...,Projede target-level egitim verisi icinde kull...
4,5,FiQA 2018 sentiment classification,https://huggingface.co/datasets/TheFinAI/fiqa-...,already_in_target_dataset_secondary_check,"822 train, 117 validation, 234 test in HF mirror",Aspect/target ve surekli sentiment skoru ile a...,Yaygin benchmark oldugu icin model asinaligi/l...
5,6,FinEntity,https://huggingface.co/datasets/yixuantt/FinEn...,already_in_target_dataset_entity_span_eval,entity span + positive/neutral/negative labels,Entity span bilgisi SEntFiNden farkli olarak m...,Projede kucuk bir bolumu hedef veri setine ekl...

## 4. Ek aday veri setlerinden 5'er ornek

Asagidaki CSV, Hugging Face uzerinden cekilebilen adaylardan ornekleri icerir. `NOSIBLE`, `SENTiVENT` ve `FNSPID` proje icin yeni kaynak havuzu olarak degerlidir; `FiQA` ve `FinEntity` ise projede kullanildigi icin burada daha cok karsilastirmali/holdout tasarimi notuyla gosterilir.

In [5]:
examples_path = EXTERNAL_CANDIDATE_DIR / "addable_dataset_examples.csv"
addable_dataset_examples = pd.read_csv(examples_path)
for dataset_name, part in addable_dataset_examples.groupby("dataset", sort=False):
    display(Markdown(f"### {dataset_name}"))
    display(part.head(5))

### NOSIBLE Financial Sentiment

,dataset,example_no,text,label,source,url,id,label_or_signal,date,target,aspect,score,type
0,NOSIBLE Financial Sentiment,1,Offshore staff HOUSTON – VAALCO Energy is look...,positive,www.offshore-mag.com,https://www.offshore-mag.com/rigs-vessels/arti...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NOSIBLE Financial Sentiment,2,"Farmingdale, N.J.-based Dialight has achieved ...",positive,www.ecmweb.com,https://www.ecmweb.com/construction/article/20...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NOSIBLE Financial Sentiment,3,"J.Jill, Inc. ( JILL ), a lifestyle brand that ...",negative,www.rttnews.com,https://www.rttnews.com/3502523/j-jill-continu...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NOSIBLE Financial Sentiment,4,Pegasystems shares have lost about 70.2% since...,negative,au.lifestyle.yahoo.com,https://au.lifestyle.yahoo.com/pegasystems-peg...,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NOSIBLE Financial Sentiment,5,Combined ratio improved 850 bps from the prior...,negative,www.zacks.com,https://www.zacks.com/stock/news/2307221/wr-be...,NaN,NaN,NaN,NaN,NaN,NaN,NaN

### SENTiVENT Bench

,dataset,example_no,text,label,source,url,id,label_or_signal,date,target,aspect,score,type
5,SENTiVENT Bench,1,"American Airlines Up on Record April Traffic ,...",NaN,sentivent annotations,NaN,aal00,"positive, positive, neutral, positive, positive",NaN,NaN,NaN,NaN,NaN
6,SENTiVENT Bench,2,$ 900M investment at PHL to bring new traffic ...,NaN,sentivent annotations,NaN,aal01,"positive, positive, positive, neutral, positive",NaN,NaN,NaN,NaN,NaN
7,SENTiVENT Bench,3,Delta Air Lines finds competition intense in M...,NaN,sentivent annotations,NaN,aal02,"negative, positive, negative, positive, positive",NaN,NaN,NaN,NaN,NaN
8,SENTiVENT Bench,4,American Airlines reports load factor increase...,NaN,sentivent annotations,NaN,aal03,"positive, positive, positive, positive, positive",NaN,NaN,NaN,NaN,NaN
9,SENTiVENT Bench,5,American Airlines Backtracks a Bit on Its Legr...,NaN,sentivent annotations,NaN,aal04,"negative, negative, neutral, neutral, negative",NaN,NaN,NaN,NaN,NaN

### FNSPID

,dataset,example_no,text,label,source,url,id,label_or_signal,date,target,aspect,score,type
10,FNSPID,1,Stocks That Hit 52-Week Highs On Friday,NaN,Benzinga Insights,https://www.benzinga.com/news/20/06/16190091/s...,NaN,NaN,2020-06-05 06:30:54 UTC,A,NaN,NaN,NaN
11,FNSPID,2,Stocks That Hit 52-Week Highs On Wednesday,NaN,Benzinga Insights,https://www.benzinga.com/news/20/06/16170189/s...,NaN,NaN,2020-06-03 06:45:20 UTC,A,NaN,NaN,NaN
12,FNSPID,3,71 Biggest Movers From Friday,NaN,Lisa Levin,https://www.benzinga.com/news/20/05/16103463/7...,NaN,NaN,2020-05-26 00:30:07 UTC,A,NaN,NaN,NaN
13,FNSPID,4,46 Stocks Moving In Friday's Mid-Day Session,NaN,Lisa Levin,https://www.benzinga.com/news/20/05/16095921/4...,NaN,NaN,2020-05-22 08:45:06 UTC,A,NaN,NaN,NaN
14,FNSPID,5,B of A Securities Maintains Neutral on Agilent...,NaN,Vick Meyer,https://www.benzinga.com/news/20/05/16095304/b...,NaN,NaN,2020-05-22 07:38:59 UTC,A,NaN,NaN,NaN

### FiQA 2018 sentiment classification

,dataset,example_no,text,label,source,url,id,label_or_signal,date,target,aspect,score,type
15,FiQA 2018 sentiment classification,1,Royal Mail chairman Donald Brydon set to step ...,NaN,NaN,NaN,1,NaN,NaN,Royal Mail,Corporate/Appointment,-0.374,headline
16,FiQA 2018 sentiment classification,2,Slump in Weir leads FTSE down from record high,NaN,NaN,NaN,100,NaN,NaN,Weir,Market/Volatility/Volatility,-0.827,headline
17,FiQA 2018 sentiment classification,3,AstraZeneca wins FDA approval for key new lung...,NaN,NaN,NaN,1000,NaN,NaN,AstraZeneca,Corporate/Regulatory,0.549,headline
18,FiQA 2018 sentiment classification,4,UPDATE 1-Lloyds to cut 945 jobs as part of 3-y...,NaN,NaN,NaN,1002,NaN,NaN,Lloyds,Corporate/Strategy,-0.266,headline
19,FiQA 2018 sentiment classification,5,Standard Chartered Shifts Emerging-Markets Str...,NaN,NaN,NaN,1005,NaN,NaN,Standard Chartered,Corporate/Strategy,-0.461,headline

### FinEntity

,dataset,example_no,text,label,source,url,id,label_or_signal,date,target,aspect,score,type
20,FinEntity,1,Johnson & Johnson <JNJ.N> shares gained 0.20% ...,Positive,NaN,NaN,NaN,NaN,NaN,Johnson & Johnson,NaN,NaN,NaN
21,FinEntity,2,"On the positive side, Siemens is rallying 6% a...",Positive; Positive,NaN,NaN,NaN,NaN,NaN,Huhtamaki; Siemens,NaN,NaN,NaN
22,FinEntity,3,Brent crude <LCOc1> rose 1.4% to $100.69 per b...,Positive; Positive,NaN,NaN,NaN,NaN,NaN,Brent crude; U.S. crude,NaN,NaN,NaN
23,FinEntity,4,"Nearly all major S&P 500 sectors are red, with...",Positive; Negative; Negative; Positive; Negative,NaN,NaN,NaN,NaN,NaN,healthcare; communications services; S&P 500; ...,NaN,NaN,NaN
24,FinEntity,5,NEW YORK - Wall Street ended sharply higher on...,Positive; Positive,NaN,NaN,NaN,NaN,NaN,Tesla; Nvidia,NaN,NaN,NaN

## 5. Kisa karar

- En guvenli yeni katki: `NOSIBLE Financial Sentiment` icinden dengeli 300-600 ornek secip iki asamali insan anotasyonu yapmak.
- En akademik ileri degerlendirme: `SENTiVENT Bench` ile event-level/implicit sentiment hata analizi eklemek.
- En buyuk olcekli tez uzantisi: `FNSPID` ile haber-sentiment sinyalini fiyat/zaman serisiyle baglamak.
- `SEntFiN`, `FiQA`, `FinEntity`: projede zaten gorundugu icin yeni dis test katkisi ancak train/test ayrimi garanti edilirse savunulabilir.