In [2]:
from pathlib import Path
import pandas as pd

PROJECT_ROOT = Path.cwd()
if PROJECT_ROOT.name == "app":
    PROJECT_ROOT = PROJECT_ROOT.parent

def read_table(path: Path) -> pd.DataFrame:
    if path.suffix == ".parquet":
        return pd.read_parquet(path)
    if path.suffix == ".csv":
        return pd.read_csv(path)
    if path.suffix in [".xlsx", ".xls"]:
        return pd.read_excel(path)
    raise ValueError(f"Desteklenmeyen dosya türü: {path}")

def inspect_dataset(name: str, path: str, label_col: str, n_rows: int = 3) -> dict:
    file_path = PROJECT_ROOT / path
    df = read_table(file_path)
    
    print("=" * 80)
    print(f"📌 VERİ SETİ: {name}")
    print(f"📁 Dosya Yolu: {path}")
    print(f"📊 Toplam Satır Sayısı (N): {len(df)}")
    print(f"\n🔍 İlk {n_rows} Satır:")
    display(df.head(n_rows))  # Jupyter / Colab kullanmıyorsanız 'display' yerine 'print' kullanabilirsiniz
    print("=" * 80 + "\n")

    # Sınıf sayılarını hesaplama
    counts = df[label_col].astype(str).str.lower().value_counts()

    return {
        "Veri seti": name,
        "N": int(len(df)),
        "Negatif": int(counts.get("negative", 0)),
        "Tarafsız": int(counts.get("neutral", 0)),
        "Pozitif": int(counts.get("positive", 0)),
    }

# Okunacak dosyaların listesi
datasets = [
    ("Eğitim", "db/splits/plain_sentiment_v1/train_df.parquet", "label"),
    ("Doğrulama", "db/splits/plain_sentiment_v1/val_df.parquet", "label"),
    ("Test", "db/splits/plain_sentiment_v1/test_df.parquet", "label"),
    ("S&P 500 dış test", "outputs/finetuned_model_results/finbert_target_finetuned_seed42/external_evaluation/sp500_external/predictions.csv", "gold_label"),
    ("Sentetik test", "outputs/finetuned_model_results/finbert_target_finetuned_seed42/external_evaluation/synthetic_external/predictions.csv", "gold_label"),
    ("Reuters dış test", "outputs/finetuned_model_results/finbert_target_finetuned_seed42/external_evaluation/reuters_external/predictions.csv", "gold_label"),
]

rows = []

# Tüm dosyaları sırayla incele ve ilk 3 satırı bas
for name, path, label_col in datasets:
    row = inspect_dataset(name, path, label_col, n_rows=3)
    rows.append(row)

================================================================================
📌 VERİ SETİ: Eğitim
📁 Dosya Yolu: db/splits/plain_sentiment_v1/train_df.parquet
📊 Toplam Satır Sayısı (N): 12950

🔍 İlk 3 Satır:

,sample_id,source_dataset,dataset_full_name,dataset_group,dataset_role,dataset_description,source_original_split,text,label,label_id,...,usable_for_main_evaluation,finbert_comparison_suitable,finbert_training_overlap_risk,finbert_comparison_note,label_source_type,row_note,metadata_json,created_at,text_norm,input_text
0,PLAIN_SENT_0005515,TwitterFinancialNewsSentiment,Twitter Financial News Sentiment,plain_sentiment,main_train_validation_test_candidate,Finansla ilişkili kısa metin/tweet veri setidi...,train,Womply 2020 State of Local Restaurants Report ...,neutral,1,...,True,True,False,ProsusAI/finbert'in bilinen fine-tuning verisi...,document_level_class_label,Plain financial sentiment row; no target/entit...,"{""source_original_split"": ""train""}",2026-05-13 13:20:23,womply 2020 state of local restaurants report ...,Womply 2020 State of Local Restaurants Report ...
1,PLAIN_SENT_0003714,TwitterFinancialNewsSentiment,Twitter Financial News Sentiment,plain_sentiment,main_train_validation_test_candidate,Finansla ilişkili kısa metin/tweet veri setidi...,train,Blackstone CEO Steve Schwarzman says the virus...,negative,0,...,True,True,False,ProsusAI/finbert'in bilinen fine-tuning verisi...,document_level_class_label,Plain financial sentiment row; no target/entit...,"{""source_original_split"": ""train""}",2026-05-13 13:20:23,blackstone ceo steve schwarzman says the virus...,Blackstone CEO Steve Schwarzman says the virus...
2,PLAIN_SENT_0002350,TwitterFinancialNewsSentiment,Twitter Financial News Sentiment,plain_sentiment,main_train_validation_test_candidate,Finansla ilişkili kısa metin/tweet veri setidi...,train,Constellation Brands goes ex-dividend on Monday,neutral,1,...,True,True,False,ProsusAI/finbert'in bilinen fine-tuning verisi...,document_level_class_label,Plain financial sentiment row; no target/entit...,"{""source_original_split"": ""train""}",2026-05-13 13:20:23,constellation brands goes ex-dividend on monday,Constellation Brands goes ex-dividend on Monday

================================================================================

================================================================================
📌 VERİ SETİ: Doğrulama
📁 Dosya Yolu: db/splits/plain_sentiment_v1/val_df.parquet
📊 Toplam Satır Sayısı (N): 1432

🔍 İlk 3 Satır:

,sample_id,source_dataset,dataset_full_name,dataset_group,dataset_role,dataset_description,source_original_split,text,label,label_id,...,usable_for_main_evaluation,finbert_comparison_suitable,finbert_training_overlap_risk,finbert_comparison_note,label_source_type,row_note,metadata_json,created_at,text_norm,input_text
0,PLAIN_SENT_0009721,TwitterFinancialNewsSentiment,Twitter Financial News Sentiment,plain_sentiment,main_train_validation_test_candidate,Finansla ilişkili kısa metin/tweet veri setidi...,validation,"Two weeks later, no change, Fed ain't stopping...",neutral,1,...,True,True,False,ProsusAI/finbert'in bilinen fine-tuning verisi...,document_level_class_label,Plain financial sentiment row; no target/entit...,"{""source_original_split"": ""validation""}",2026-05-13 13:20:23,"two weeks later, no change, fed ain't stopping...","Two weeks later, no change, Fed ain't stopping..."
1,PLAIN_SENT_0006221,TwitterFinancialNewsSentiment,Twitter Financial News Sentiment,plain_sentiment,main_train_validation_test_candidate,Finansla ilişkili kısa metin/tweet veri setidi...,train,Indonesia Braces for Export Hit as Virus Saps ...,negative,0,...,True,True,False,ProsusAI/finbert'in bilinen fine-tuning verisi...,document_level_class_label,Plain financial sentiment row; no target/entit...,"{""source_original_split"": ""train""}",2026-05-13 13:20:23,indonesia braces for export hit as virus saps ...,Indonesia Braces for Export Hit as Virus Saps ...
2,PLAIN_SENT_0005956,TwitterFinancialNewsSentiment,Twitter Financial News Sentiment,plain_sentiment,main_train_validation_test_candidate,Finansla ilişkili kısa metin/tweet veri setidi...,train,AlayaCare Announces Acquisition of Arrow Solut...,neutral,1,...,True,True,False,ProsusAI/finbert'in bilinen fine-tuning verisi...,document_level_class_label,Plain financial sentiment row; no target/entit...,"{""source_original_split"": ""train""}",2026-05-13 13:20:23,alayacare announces acquisition of arrow solut...,AlayaCare Announces Acquisition of Arrow Solut...

================================================================================

================================================================================
📌 VERİ SETİ: Test
📁 Dosya Yolu: db/splits/plain_sentiment_v1/test_df.parquet
📊 Toplam Satır Sayısı (N): 2386

🔍 İlk 3 Satır:

,sample_id,source_dataset,dataset_full_name,dataset_group,dataset_role,dataset_description,source_original_split,text,label,label_id,...,usable_for_main_evaluation,finbert_comparison_suitable,finbert_training_overlap_risk,finbert_comparison_note,label_source_type,row_note,metadata_json,created_at,text_norm,input_text
0,PLAIN_SENT_0001645,TwitterFinancialNewsSentiment,Twitter Financial News Sentiment,plain_sentiment,main_train_validation_test_candidate,Finansla ilişkili kısa metin/tweet veri setidi...,train,Looking Through The Smoke To Altria’s Future,neutral,1,...,True,True,False,ProsusAI/finbert'in bilinen fine-tuning verisi...,document_level_class_label,Plain financial sentiment row; no target/entit...,"{""source_original_split"": ""train""}",2026-05-13 13:20:23,looking through the smoke to altria’s future,Looking Through The Smoke To Altria’s Future
1,PLAIN_SENT_0000351,TwitterFinancialNewsSentiment,Twitter Financial News Sentiment,plain_sentiment,main_train_validation_test_candidate,Finansla ilişkili kısa metin/tweet veri setidi...,train,Westlake Chemical stock price target raised to...,positive,2,...,True,True,False,ProsusAI/finbert'in bilinen fine-tuning verisi...,document_level_class_label,Plain financial sentiment row; no target/entit...,"{""source_original_split"": ""train""}",2026-05-13 13:20:23,westlake chemical stock price target raised to...,Westlake Chemical stock price target raised to...
2,PLAIN_SENT_0011818,TwitterFinancialNewsSentiment,Twitter Financial News Sentiment,plain_sentiment,main_train_validation_test_candidate,Finansla ilişkili kısa metin/tweet veri setidi...,validation,"QD, HEXO among premarket losers",negative,0,...,True,True,False,ProsusAI/finbert'in bilinen fine-tuning verisi...,document_level_class_label,Plain financial sentiment row; no target/entit...,"{""source_original_split"": ""validation""}",2026-05-13 13:20:23,"qd, hexo among premarket losers","QD, HEXO among premarket losers"

================================================================================

================================================================================
📌 VERİ SETİ: S&P 500 dış test
📁 Dosya Yolu: outputs/finetuned_model_results/finbert_target_finetuned_seed42/external_evaluation/sp500_external/predictions.csv
📊 Toplam Satır Sayısı (N): 1060

🔍 İlk 3 Satır:

,sample_id,annotation_id,date,source_file,eval_text,gold_label,gold_id,prediction_id,prediction,confidence,prob_negative,prob_neutral,prob_positive,correct
0,SP500_HEAD_000004,SP500_ANN_0001,2008-01-03,SP500_annotation_batch_001.xlsx,"U.S. Stocks Higher After Economic Data, Monsan...",positive,2,2,positive,0.998953,0.000367,0.000681,0.998953,True
1,SP500_HEAD_016918,SP500_ANN_0002,2023-12-15,SP500_annotation_batch_001.xlsx,Stock Market Outlook 2024: Rare Bullish Signal...,positive,2,2,positive,0.998657,0.000598,0.000745,0.998657,True
2,SP500_HEAD_013289,SP500_ANN_0003,2023-03-20,SP500_annotation_batch_001.xlsx,Federal Reserve Rate Hike Odds Grow As Bank-Cr...,positive,2,2,positive,0.998113,0.000452,0.001435,0.998113,True

================================================================================

================================================================================
📌 VERİ SETİ: Sentetik test
📁 Dosya Yolu: outputs/finetuned_model_results/finbert_target_finetuned_seed42/external_evaluation/synthetic_external/predictions.csv
📊 Toplam Satır Sayısı (N): 3000

🔍 İlk 3 Satır:

,sample_id,annotation_id,date,source_file,eval_text,gold_label,gold_id,prediction_id,prediction,confidence,prob_negative,prob_neutral,prob_positive,correct
0,SYN_NEG_HEAD_000821,SYN_NEG_ANN_0821,2026-04-01 00:00:00,negative_batch_000.xlsx,A cybersecurity vendor reported slower billing...,negative,0,0,negative,0.998713,0.998713,0.001035,0.000252,True
1,SYN_NEG_HEAD_000822,SYN_NEG_ANN_0822,2026-04-02 00:00:00,negative_batch_000.xlsx,A consumer finance company increased reserves ...,negative,0,1,neutral,0.990346,0.006199,0.990346,0.003454,False
2,SYN_NEG_HEAD_000823,SYN_NEG_ANN_0823,2026-04-03 00:00:00,negative_batch_000.xlsx,A hospital operator cut earnings guidance afte...,negative,0,0,negative,0.998934,0.998934,0.000769,0.000297,True

================================================================================

================================================================================
📌 VERİ SETİ: Reuters dış test
📁 Dosya Yolu: outputs/finetuned_model_results/finbert_target_finetuned_seed42/external_evaluation/reuters_external/predictions.csv
📊 Toplam Satır Sayısı (N): 5000

🔍 İlk 3 Satır:

,sample_id,annotation_id,date,source_file,eval_text,gold_label,gold_id,prediction_id,prediction,confidence,prob_negative,prob_neutral,prob_positive,correct
0,reuters_external_000000,REUTERS_ANN_00001,2007-04-12,REUTERS_annotation_batch_001.xlsx,s.africa watchdog to probe gold fields bid report,negative,0,1,neutral,0.913808,0.085477,0.913808,0.000715,False
1,reuters_external_000001,REUTERS_ANN_00002,2007-04-26,REUTERS_annotation_batch_001.xlsx,new barbie girls sashay into view with mp-3,positive,2,1,neutral,0.999144,0.000391,0.999144,0.000464,False
2,reuters_external_000002,REUTERS_ANN_00003,2006-12-17,REUTERS_annotation_batch_001.xlsx,"stocks await data, mergers and santa",neutral,1,1,neutral,0.999421,0.000396,0.999421,0.000182,True

================================================================================