# 20 - Reuters + S&P500: 5.000'er ek annotation

Amaç: Daha önce annotate edilmiş kayıtları RAW veri setlerinden çıkarmak,
kalan havuzdan 5.000 Reuters + 5.000 S&P500 örneği seçmek ve bunları
ChatGPT + Gemini ile yeniden etiketlemek.

Checkpoint: Her 5'li batch sonrası diske yazılır.
Resume: Notebook kesilirse aynı aday örnekleri ve checkpoint'ler kullanılır.

Yeni seçilen örneklerde insan/reference etiketi yoktur. Bu yüzden bu notebook
yeni 10.000 kayıt için ChatGPT ↔ Gemini agreement ve Cohen's Kappa hesaplar.

In [1]:
%pip install -q -U openai google-genai pandas numpy scikit-learn

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
from pathlib import Path
import os
import re
import json
import math
import time
import gc
from getpass import getpass

import pandas as pd
import numpy as np
from IPython.display import display
from sklearn.metrics import cohen_kappa_score

pd.set_option("display.max_columns", 100)
pd.set_option("display.max_colwidth", 180)
pd.set_option("display.width", 220)

VALID_LABELS = ["negative", "neutral", "positive"]

RAW_DIR = Path(
    r"D:\serkan.kaymak\financial_sentiment_thesis"
    r"\financial_sentiment_thesis\db\raw"
)

REUTERS_DIR = RAW_DIR / "ReutersNews106521_parts"
SP500_PATH = RAW_DIR / "sp500_headlines_2008_2024_raw.csv"

OLD_CONSENSUS_PATH = Path(
    r"D:\serkan.kaymak\financial_sentiment_thesis"
    r"\financial_sentiment_thesis\db\processed"
    r"\gemini_consensus_2024\all_consensus_combined.csv"
)

OLD_REUTERS_FULL_PATH = Path(
    r"D:\serkan.kaymak\financial_sentiment_thesis"
    r"\financial_sentiment_thesis\db\annotations"
    r"\gemini\reuters_gemini_labeled.csv"
)

OLD_SP500_FULL_PATH = Path(
    r"D:\serkan.kaymak\financial_sentiment_thesis"
    r"\financial_sentiment_thesis\db\annotations"
    r"\gemini\sp500_gemini_labeled.csv"
)

OUTPUT_DIR = RAW_DIR.parent / "annotations" / "additional_5000_2026"
CHECKPOINT_DIR = OUTPUT_DIR / "checkpoints"
CANDIDATE_DIR = OUTPUT_DIR / "candidates"
FINAL_DIR = OUTPUT_DIR / "final"
RESULT_DIR = OUTPUT_DIR / "results"

for p in [OUTPUT_DIR, CHECKPOINT_DIR, CANDIDATE_DIR, FINAL_DIR, RESULT_DIR]:
    p.mkdir(parents=True, exist_ok=True)

N_PER_DATASET = 5000
BATCH_SIZE = 5
RANDOM_STATE = 42

# Daha önce çalıştırıp doğruladığın modeller.
OPENAI_MODEL = "gpt-5.6-luna"
GEMINI_MODEL = "gemini-3.5-flash-lite"

OPENAI_REQUEST_INTERVAL = 0.5
GEMINI_REQUEST_INTERVAL = 5.0
MAX_RETRIES = 8

print("=" * 110)
print("20 - ADDITIONAL 5,000 + 5,000")
print("=" * 110)
print("Reuters dir :", REUTERS_DIR)
print("S&P500 raw  :", SP500_PATH)
print("Old consensus:", OLD_CONSENSUS_PATH)
print("Output      :", OUTPUT_DIR)
print("N/dataset   :", N_PER_DATASET)
print("Batch       :", BATCH_SIZE)

==============================================================================================================
20 - ADDITIONAL 5,000 + 5,000
==============================================================================================================
Reuters dir : D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\raw\ReutersNews106521_parts
S&P500 raw  : D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\raw\sp500_headlines_2008_2024_raw.csv
Old consensus: D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\processed\gemini_consensus_2024\all_consensus_combined.csv
Output      : D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\annotations\additional_5000_2026
N/dataset   : 5000
Batch       : 5

## 1. Reuters RAW'ın tüm partlarını oku

In [3]:
reuters_part_paths = sorted(
    REUTERS_DIR.glob("reuters_part_*.parquet")
)

if not reuters_part_paths:
    raise FileNotFoundError(
        f"Reuters part dosyası bulunamadı: {REUTERS_DIR}"
    )

reuters_parts = []

for p in reuters_part_paths:
    part = pd.read_parquet(p)
    print(f"{p.name}: {part.shape}")
    reuters_parts.append(part)

reuters_df = pd.concat(
    reuters_parts,
    ignore_index=True
)

del reuters_parts
gc.collect()

print("\nReuters toplam:", reuters_df.shape)
print("Kolonlar:", reuters_df.columns.tolist())
display(reuters_df.head(3))

reuters_part_1.parquet: (21304, 9)
reuters_part_2.parquet: (21304, 9)
reuters_part_3.parquet: (21304, 9)

Reuters toplam: (63912, 9)
Kolonlar: ['source_dataset', 'date_folder', 'date', 'title', 'author', 'url', 'text', 'file_name', 'file_path']

,source_dataset,date_folder,date,title,author,url,text,file_name,file_path
0,ReutersNews106521,20061020,"Fri Oct 20, 2006 6:15pm EDT",Exxon Mobil offers plan to end Alaska dispute,Yereth Rosen,http://www.reuters.com/article/2006/10/20/businesspro-energy-exxonmobil-alaska-dc-idUSN2021166720061020,"ANCHORAGE, Alaska (Reuters) - Exxon Mobil ( XOM.N ) offered to pay a $20 million fine and relinquish some leases to the state of Alaska to resolve a dispute over a North Slope...",businesspro-energy-exxonmobil-alaska-dc-idUSN2021166720061020,E:\serkan.kaymak\coin-news-analyses\financial-prediction-thesis\db\finansNews\financial-news-dataset-master\ReutersNews106521\20061020\businesspro-energy-exxonmobil-alaska-dc-i...
1,ReutersNews106521,20061020,"Fri Oct 20, 2006 4:25pm EDT","Hey buddy, can you spare $600 for a Google share?",Eric Auchard and Paul Thomasch,http://www.reuters.com/article/2006/10/20/businesspro-google-dc-idUSN2036351320061020,"SAN FRANCISCO/NEW YORK (Reuters) - Wall Street analysts raced to outdo one another on Friday in raising stock price targets on Google Inc. ( GOOG.O ), with the most aggressive...",businesspro-google-dc-idUSN2036351320061020,E:\serkan.kaymak\coin-news-analyses\financial-prediction-thesis\db\finansNews\financial-news-dataset-master\ReutersNews106521\20061020\businesspro-google-dc-idUSN2036351320061020
2,ReutersNews106521,20061021,"Sat Oct 21, 2006 2:21pm EDT",AOL CEO says sales may shrink for two years -paper,,http://www.reuters.com/article/2006/10/21/businesspro-aol-sales-dc-idUSL2176365120061021,"FRANKFURT (Reuters) - Internet service provider AOL's sales may shrink for the next two years as it gives away services to win more users and attract advertising, its chief ex...",businesspro-aol-sales-dc-idUSL2176365120061021,E:\serkan.kaymak\coin-news-analyses\financial-prediction-thesis\db\finansNews\financial-news-dataset-master\ReutersNews106521\20061021\businesspro-aol-sales-dc-idUSL21763651200...

## 2. S&P500 RAW'ı oku

In [4]:
if not SP500_PATH.exists():
    raise FileNotFoundError(
        f"S&P500 dosyası bulunamadı: {SP500_PATH}"
    )

sp500_df = pd.read_csv(
    SP500_PATH,
    low_memory=False
)

print("S&P500:", sp500_df.shape)
print("Kolonlar:", sp500_df.columns.tolist())
display(sp500_df.head(3))

S&P500: (19127, 3)
Kolonlar: ['Title', 'Date', 'CP']

                                                       Title        Date       CP
0           JPMorgan Predicts 2008 Will Be "Nothing But Net"  2008-01-02  1447.16
1  Dow Tallies Biggest First-session-of-year Point Drop Ever  2008-01-02  1447.16
2                           2008 predictions for the S&P 500  2008-01-02  1447.16

## 3. Annotation text kolonlarını belirle

In [5]:
def choose_text_column(df, candidates, dataset_name):
    for col in candidates:
        if col in df.columns:
            s = df[col].astype("string")
            if (s.notna() & s.str.strip().ne("")).any():
                print(
                    f"{dataset_name} annotation text kolonu: {col}"
                )
                return col

    raise ValueError(
        f"{dataset_name} için uygun text kolonu bulunamadı. "
        f"Kolonlar: {df.columns.tolist()}"
    )


REUTERS_TEXT_COL = choose_text_column(
    reuters_df,
    ["title", "text_en", "headline", "text", "article_text", "content", "body"],
    "Reuters"
)

SP500_TEXT_COL = choose_text_column(
    sp500_df,
    ["Title", "text_en", "text", "headline", "title", "news", "article", "content"],
    "S&P500"
)

reuters_df["annotation_text"] = (
    reuters_df[REUTERS_TEXT_COL]
    .astype("string")
    .fillna("")
    .str.strip()
)

sp500_df["annotation_text"] = (
    sp500_df[SP500_TEXT_COL]
    .astype("string")
    .fillna("")
    .str.strip()
)

Reuters annotation text kolonu: title
S&P500 annotation text kolonu: Title

## 4. Normalize + raw duplicate temizliği

In [6]:
def normalize_text(text):
    text = str(text).replace("\u00a0", " ")
    text = re.sub(r"\s+", " ", text)
    return text.strip().lower()


def normalize_url(value):
    if value is None:
        return ""
    value = str(value).strip().lower()
    if value in {"nan", "none", "<na>"}:
        return ""
    return value.rstrip("/")


def find_optional_column(df, candidates):
    for col in candidates:
        if col in df.columns:
            return col
    return None


def add_keys(df):
    df = df.copy()

    df["text_key"] = df["annotation_text"].map(
        normalize_text
    )

    url_col = find_optional_column(
        df,
        ["url", "link", "source_url", "news_url"]
    )

    if url_col:
        df["url_key"] = df[url_col].map(
            normalize_url
        )
    else:
        df["url_key"] = ""

    return df


reuters_df = add_keys(reuters_df)
sp500_df = add_keys(sp500_df)

reuters_df = reuters_df[
    reuters_df["text_key"].ne("")
].copy()

sp500_df = sp500_df[
    sp500_df["text_key"].ne("")
].copy()

print(
    "Reuters raw text duplicate:",
    reuters_df["text_key"].duplicated().sum()
)

print(
    "S&P500 raw text duplicate:",
    sp500_df["text_key"].duplicated().sum()
)

reuters_df = (
    reuters_df
    .drop_duplicates("text_key", keep="first")
    .reset_index(drop=True)
)

sp500_df = (
    sp500_df
    .drop_duplicates("text_key", keep="first")
    .reset_index(drop=True)
)

print("Reuters unique:", len(reuters_df))
print("S&P500 unique :", len(sp500_df))

Reuters raw text duplicate: 5527
S&P500 raw text duplicate: 1087
Reuters unique: 58346
S&P500 unique : 18040

## 5. Eski annotation dosyalarını yükle

Consensus dosyası kullanıcı tarafından verilen ana eski dosyadır.
Full old annotation dosyaları varsa ayrıca kullanılır; bu sayede
eski disagreement kayıtlarını da yeni örneklemden çıkarmış oluruz.

In [7]:
def safe_read_csv(path):
    path = Path(path)

    if not path.exists():
        print(f"⚠️ Yok, atlanıyor: {path}")
        return None

    df = pd.read_csv(
        path,
        encoding="utf-8-sig",
        low_memory=False
    )

    print(
        f"✓ {path.name}: {df.shape}"
    )

    return df


old_consensus_df = safe_read_csv(
    OLD_CONSENSUS_PATH
)

old_reuters_df = safe_read_csv(
    OLD_REUTERS_FULL_PATH
)

old_sp500_df = safe_read_csv(
    OLD_SP500_FULL_PATH
)

✓ all_consensus_combined.csv: (4721, 6)
✓ reuters_gemini_labeled.csv: (5000, 6)
✓ sp500_gemini_labeled.csv: (1030, 6)

## 6. Eski annotation key'lerini çıkar

In [8]:
def extract_keys(df):
    if df is None or df.empty:
        return set(), set()

    text_col = None

    for col in [
        "text",
        "text_en",
        "annotation_text",
        "headline",
        "title",
        "content",
        "article"
    ]:
        if col in df.columns:
            text_col = col
            break

    text_keys = set()

    if text_col is not None:
        text_keys = set(
            df[text_col]
            .dropna()
            .astype(str)
            .map(normalize_text)
        )
        text_keys.discard("")

    url_col = find_optional_column(
        df,
        ["url", "link", "source_url", "news_url"]
    )

    url_keys = set()

    if url_col is not None:
        url_keys = set(
            df[url_col]
            .dropna()
            .astype(str)
            .map(normalize_url)
        )
        url_keys.discard("")

    return text_keys, url_keys


consensus_reuters = None
consensus_sp500 = None

if old_consensus_df is not None:
    if "source_dataset" in old_consensus_df.columns:
        source = (
            old_consensus_df["source_dataset"]
            .astype("string")
            .fillna("")
            .str.lower()
        )

        consensus_reuters = old_consensus_df[
            source.str.contains(
                "reuters",
                na=False
            )
        ].copy()

        consensus_sp500 = old_consensus_df[
            source.str.contains(
                "sp500|s&p|sp_500",
                regex=True,
                na=False
            )
        ].copy()

print(
    "Consensus Reuters:",
    0 if consensus_reuters is None else len(consensus_reuters)
)

print(
    "Consensus S&P500:",
    0 if consensus_sp500 is None else len(consensus_sp500)
)

reuters_old_frames = [
    x for x in [
        consensus_reuters,
        old_reuters_df
    ]
    if x is not None and not x.empty
]

sp500_old_frames = [
    x for x in [
        consensus_sp500,
        old_sp500_df
    ]
    if x is not None and not x.empty
]

reuters_old_all = (
    pd.concat(
        reuters_old_frames,
        ignore_index=True
    )
    if reuters_old_frames
    else None
)

sp500_old_all = (
    pd.concat(
        sp500_old_frames,
        ignore_index=True
    )
    if sp500_old_frames
    else None
)

reuters_old_text_keys, reuters_old_url_keys = (
    extract_keys(reuters_old_all)
)

sp500_old_text_keys, sp500_old_url_keys = (
    extract_keys(sp500_old_all)
)

print(
    "\nOld Reuters text keys:",
    len(reuters_old_text_keys)
)

print(
    "Old Reuters URL keys:",
    len(reuters_old_url_keys)
)

print(
    "Old S&P500 text keys:",
    len(sp500_old_text_keys)
)

print(
    "Old S&P500 URL keys:",
    len(sp500_old_url_keys)
)

Consensus Reuters: 3842
Consensus S&P500: 879

Old Reuters text keys: 5000
Old Reuters URL keys: 0
Old S&P500 text keys: 1030
Old S&P500 URL keys: 0

## 7. Daha önce annotate edilmişleri ele

In [9]:
def remove_old_annotations(
    df,
    old_text_keys,
    old_url_keys,
    dataset_name
):
    df = df.copy()

    text_hit = df["text_key"].isin(
        old_text_keys
    )

    url_hit = (
        df["url_key"].ne("")
        &
        df["url_key"].isin(
            old_url_keys
        )
    )

    hit = text_hit | url_hit

    remaining = df[
        ~hit
    ].copy()

    print("=" * 100)
    print(dataset_name)
    print("=" * 100)
    print(
        "Raw unique       :",
        len(df)
    )
    print(
        "Old annotation   :",
        int(hit.sum())
    )
    print(
        "New candidates   :",
        len(remaining)
    )

    return remaining


reuters_candidates = remove_old_annotations(
    reuters_df,
    reuters_old_text_keys,
    reuters_old_url_keys,
    "REUTERS"
)

sp500_candidates = remove_old_annotations(
    sp500_df,
    sp500_old_text_keys,
    sp500_old_url_keys,
    "S&P500"
)

====================================================================================================
REUTERS
====================================================================================================
Raw unique       : 58346
Old annotation   : 3641
New candidates   : 54705

====================================================================================================
S&P500
====================================================================================================
Raw unique       : 18040
Old annotation   : 1030
New candidates   : 17010

## 8. 5.000'er örneklemi bir kere seç ve sabitle

In [10]:
REUTERS_CANDIDATE_PATH = (
    CANDIDATE_DIR /
    "reuters_additional_5000_candidates.parquet"
)

SP500_CANDIDATE_PATH = (
    CANDIDATE_DIR /
    "sp500_additional_5000_candidates.parquet"
)


def select_or_load_sample(
    candidates,
    n,
    path,
    dataset_name
):
    path = Path(path)

    if path.exists():
        selected = pd.read_parquet(
            path
        )

        if len(selected) != n:
            raise ValueError(
                f"{dataset_name} candidate dosyası {n} değil: "
                f"{len(selected)}"
            )

        print(
            f"✓ {dataset_name}: "
            f"mevcut sabit aday örneklemi kullanılıyor."
        )

        return selected

    if len(candidates) < n:
        raise ValueError(
            f"{dataset_name}: "
            f"{n:,} kayıt gerekiyor, "
            f"{len(candidates):,} aday var."
        )

    selected = (
        candidates
        .sample(
            n=n,
            random_state=RANDOM_STATE
        )
        .reset_index(drop=True)
        .copy()
    )

    selected["annotation_id"] = [
        f"{dataset_name.lower()}_additional_{i:05d}"
        for i in range(1, n + 1)
    ]

    selected["dataset"] = dataset_name

    selected.to_parquet(
        path,
        index=False,
        compression="zstd"
    )

    print(
        f"✓ {dataset_name}: "
        f"{n:,} aday kaydedildi."
    )

    return selected


reuters_selected = select_or_load_sample(
    reuters_candidates,
    N_PER_DATASET,
    REUTERS_CANDIDATE_PATH,
    "Reuters"
)

sp500_selected = select_or_load_sample(
    sp500_candidates,
    N_PER_DATASET,
    SP500_CANDIDATE_PATH,
    "SP500"
)

print("\nReuters selected:", len(reuters_selected))
print("S&P500 selected :", len(sp500_selected))

✓ Reuters: mevcut sabit aday örneklemi kullanılıyor.
✓ SP500: mevcut sabit aday örneklemi kullanılıyor.

Reuters selected: 5000
S&P500 selected : 5000

## 9. API key

In [11]:
OPENAI_API_KEY = "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";

if not OPENAI_API_KEY:
    OPENAI_API_KEY = getpass(
        "OPENAI_API_KEY girin: "
    ).strip()

if not OPENAI_API_KEY:
    raise RuntimeError(
        "OPENAI_API_KEY bulunamadı."
    )


GEMINI_API_KEY ="AQ.Ab8RN6IVVX_2kWKkap7nUDkXllD4tl9j5KY4E5s7FF86rZ3huA";

if not GEMINI_API_KEY:
    GEMINI_API_KEY = getpass(
        "GEMINI_API_KEY girin: "
    ).strip()

if not GEMINI_API_KEY:
    raise RuntimeError(
        "GEMINI_API_KEY bulunamadı."
    )

print("✅ OpenAI key bulundu.")
print("✅ Gemini key bulundu.")

✅ OpenAI key bulundu.
✅ Gemini key bulundu.

In [12]:
from openai import OpenAI
from google import genai
from google.genai import types

openai_client = OpenAI(
    api_key=OPENAI_API_KEY
)

gemini_client = genai.Client(
    api_key=GEMINI_API_KEY,
    http_options=types.HttpOptions(
        timeout=60000
    )
)

print("✅ OpenAI client hazır.")
print("✅ Gemini client hazır.")

✅ OpenAI client hazır.
✅ Gemini client hazır.

## 10. Ortak finansal sentiment prompt'u

In [13]:
PROMPT_TEMPLATE = """
You are an expert financial sentiment annotator.

Your task is to classify the OVERALL FINANCIAL SENTIMENT of each
financial text, financial news article, headline, or sentence.

You MUST assign exactly ONE label:

- positive
- negative
- neutral

IMPORTANT:
Classify the meaning and financial implication of the WHOLE text.
Do NOT classify based on individual words.

positive:
The text communicates an overall favorable financial or business development.

negative:
The text communicates an overall unfavorable financial or business development.

neutral:
The text is primarily factual, descriptive, procedural, or informational
and does not communicate a clearly favorable or unfavorable financial implication.

CRITICAL RULES

1. Do not classify from individual positive/negative words alone.
2. Consider the overall financial implication.
3. Consider comparisons with expectations.
4. If positive and negative information both occur:
   use the main financial implication.
   If neither direction clearly dominates, use neutral.
5. NEVER return "mixed".
6. Do not use outside knowledge.
7. Preserve input order.
8. Return exactly one label per input item.

OUTPUT FORMAT

Return JSON only:

{{"labels": ["positive", "neutral", "negative"]}}

The labels array MUST contain exactly one label for every input item.

ITEMS:

{items}
"""


def build_prompt(texts):
    items = [
        {
            "index": i,
            "text": str(text)
        }
        for i, text in enumerate(texts)
    ]

    return PROMPT_TEMPLATE.format(
        items=json.dumps(
            items,
            ensure_ascii=False
        )
    )

## 11. Parser / retry

In [14]:
def normalize_label(value):
    value = (
        str(value)
        .strip()
        .lower()
    )

    if value not in VALID_LABELS:
        raise ValueError(
            f"Geçersiz label: {value!r}"
        )

    return value


def parse_labels_json(
    raw,
    expected_count
):
    if not raw:
        raise RuntimeError(
            "Boş model cevabı."
        )

    try:
        data = json.loads(
            raw
        )
    except json.JSONDecodeError as e:
        raise RuntimeError(
            f"Geçersiz JSON: {raw!r}"
        ) from e

    labels = data.get(
        "labels"
    )

    if not isinstance(
        labels,
        list
    ):
        raise RuntimeError(
            "labels listesi bulunamadı."
        )

    if len(labels) != expected_count:
        raise RuntimeError(
            f"Beklenen {expected_count}, "
            f"gelen {len(labels)}"
        )

    return [
        normalize_label(x)
        for x in labels
    ]


def retry_sleep(
    retry_no,
    error,
    provider
):
    wait_seconds = min(
        5 * (2 ** (retry_no - 1)),
        120
    )

    print(
        f"⚠️ {provider} hata | "
        f"Retry {retry_no}/{MAX_RETRIES} | "
        f"{wait_seconds}s"
    )

    print(
        str(error)[:600]
    )

    time.sleep(
        wait_seconds
    )

## 12. ChatGPT batch

In [15]:
def ask_chatgpt_batch(texts):

    prompt = build_prompt(
        texts
    )

    for retry_no in range(
        1,
        MAX_RETRIES + 1
    ):

        try:

            response = openai_client.responses.create(
                model=OPENAI_MODEL,
                input=prompt,
                text={
                    "format": {
                        "type": "json_schema",
                        "name": "financial_sentiment_labels",
                        "strict": True,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "labels": {
                                    "type": "array",
                                    "items": {
                                        "type": "string",
                                        "enum": VALID_LABELS
                                    }
                                }
                            },
                            "required": ["labels"],
                            "additionalProperties": False
                        }
                    }
                }
            )

            return parse_labels_json(
                response.output_text,
                len(texts)
            )

        except KeyboardInterrupt:
            raise

        except Exception as e:

            if retry_no >= MAX_RETRIES:
                raise RuntimeError(
                    "ChatGPT batch başarısız."
                ) from e

            retry_sleep(
                retry_no,
                e,
                "ChatGPT"
            )

## 13. Gemini batch

In [16]:
def ask_gemini_batch(texts):

    prompt = build_prompt(
        texts
    )

    for retry_no in range(
        1,
        MAX_RETRIES + 1
    ):

        try:

            response = gemini_client.models.generate_content(
                model=GEMINI_MODEL,
                contents=prompt,
                config=types.GenerateContentConfig(
                    temperature=0.0,
                    response_mime_type="application/json",
                )
            )

            return parse_labels_json(
                response.text,
                len(texts)
            )

        except KeyboardInterrupt:
            raise

        except Exception as e:

            if retry_no >= MAX_RETRIES:
                raise RuntimeError(
                    "Gemini batch başarısız."
                ) from e

            retry_sleep(
                retry_no,
                e,
                "Gemini"
            )

## 14. API test

In [17]:
TEST_TEXT = (
    "Revenue for the quarter increased by 15% "
    "compared to last year."
)

print(
    "ChatGPT test:",
    ask_chatgpt_batch(
        [TEST_TEXT]
    )
)

print(
    "Gemini test:",
    ask_gemini_batch(
        [TEST_TEXT]
    )
)

Direct use of automatic function calling (AFC) in Models.generate_content is not recommended. Instead, we recommend to use AFC in Chat.send_message. Similarly, direct use of AFC in Models.generate_content_stream is not recommended. Instead, we recommend to use AFC in Chat.send_message_stream.

ChatGPT test: ['positive']
Gemini test: ['positive']

## 15. Checkpoint

In [18]:
def checkpoint_path(
    dataset_name,
    provider
):
    return (
        CHECKPOINT_DIR
        /
        f"{dataset_name.lower()}_{provider}_checkpoint.csv"
    )


def load_checkpoint(path):
    path = Path(path)

    if (
        not path.exists()
        or path.stat().st_size == 0
    ):
        return pd.DataFrame(
            columns=[
                "annotation_id",
                "text_key",
                "text",
                "label"
            ]
        )

    df = pd.read_csv(
        path,
        encoding="utf-8-sig",
        dtype=str
    )

    if df.empty:
        return pd.DataFrame(
            columns=[
                "annotation_id",
                "text_key",
                "text",
                "label"
            ]
        )

    df["label"] = (
        df["label"]
        .astype("string")
        .str.lower()
        .str.strip()
    )

    return (
        df[
            df["label"].isin(
                VALID_LABELS
            )
        ]
        .drop_duplicates(
            "annotation_id",
            keep="last"
        )
        .reset_index(drop=True)
    )


def append_checkpoint(
    path,
    rows
):
    path = Path(path)

    batch_df = pd.DataFrame(
        rows
    )

    if batch_df.empty:
        return

    write_header = (
        not path.exists()
        or path.stat().st_size == 0
    )

    batch_df.to_csv(
        path,
        mode="a",
        header=write_header,
        index=False,
        encoding="utf-8-sig"
    )

## 16. Provider runner

In [19]:
def run_provider(
    df,
    dataset_name,
    provider,
    label_func,
    interval_seconds
):
    current_df = df.copy()

    label_col = (
        f"{provider}_label"
    )

    current_df[label_col] = pd.NA

    ckpt_path = checkpoint_path(
        dataset_name,
        provider
    )

    checkpoint = load_checkpoint(
        ckpt_path
    )

    if not checkpoint.empty:
        label_map = (
            checkpoint
            .set_index(
                "annotation_id"
            )["label"]
            .to_dict()
        )

        current_df[label_col] = (
            current_df["annotation_id"]
            .map(label_map)
        )

    done_mask = (
        current_df[label_col]
        .isin(
            VALID_LABELS
        )
    )

    remaining = (
        current_df.index[
            ~done_mask
        ]
        .tolist()
    )

    total_batches = math.ceil(
        len(remaining) / BATCH_SIZE
    ) if remaining else 0

    print("\n" + "#" * 110)
    print(
        f"{provider.upper()} | {dataset_name}"
    )
    print("#" * 110)
    print("Toplam       :", len(current_df))
    print("Checkpoint   :", int(done_mask.sum()))
    print("Kalan        :", len(remaining))
    print("Batch        :", total_batches)
    print("Checkpoint   :", ckpt_path)

    last_call_ts = 0.0

    for batch_no, start in enumerate(
        range(
            0,
            len(remaining),
            BATCH_SIZE
        ),
        start=1
    ):

        batch_indices = remaining[
            start:start + BATCH_SIZE
        ]

        texts = [
            str(
                current_df.loc[
                    idx,
                    "annotation_text"
                ]
            )
            for idx in batch_indices
        ]

        elapsed = (
            time.time()
            - last_call_ts
        )

        if (
            last_call_ts > 0
            and elapsed < interval_seconds
        ):
            time.sleep(
                interval_seconds
                - elapsed
            )

        print(
            f"[{batch_no}/{total_batches}] "
            f"{dataset_name} | "
            f"{provider} | "
            f"{len(batch_indices)} kayıt"
        )

        labels = label_func(
            texts
        )

        if len(labels) != len(
            batch_indices
        ):
            raise RuntimeError(
                "API label sayısı batch ile uyuşmuyor."
            )

        last_call_ts = time.time()

        checkpoint_rows = []

        for idx, label in zip(
            batch_indices,
            labels
        ):

            annotation_id = str(
                current_df.loc[
                    idx,
                    "annotation_id"
                ]
            )

            text_key = str(
                current_df.loc[
                    idx,
                    "text_key"
                ]
            )

            text = str(
                current_df.loc[
                    idx,
                    "annotation_text"
                ]
            )

            current_df.loc[
                idx,
                label_col
            ] = label

            checkpoint_rows.append({
                "annotation_id": annotation_id,
                "text_key": text_key,
                "text": text,
                "label": label
            })

        append_checkpoint(
            ckpt_path,
            checkpoint_rows
        )

        completed = int(
            current_df[label_col]
            .isin(VALID_LABELS)
            .sum()
        )

        print(
            f"  ✅ checkpoint | "
            f"{completed:,}/{len(current_df):,}"
        )

    return current_df

## 17. Reuters — 5.000 ChatGPT + Gemini

In [20]:
reuters_chatgpt = run_provider(
    reuters_selected,
    "Reuters",
    "chatgpt",
    ask_chatgpt_batch,
    OPENAI_REQUEST_INTERVAL
)

reuters_final = run_provider(
    reuters_chatgpt,
    "Reuters",
    "gemini",
    ask_gemini_batch,
    GEMINI_REQUEST_INTERVAL
)

print("✅ Reuters tamam.")

##############################################################################################################
CHATGPT | Reuters
##############################################################################################################
Toplam       : 5000
Checkpoint   : 5000
Kalan        : 0
Batch        : 0
Checkpoint   : D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\annotations\additional_5000_2026\checkpoints\reuters_chatgpt_checkpoint.csv

##############################################################################################################
GEMINI | Reuters
##############################################################################################################
Toplam       : 5000
Checkpoint   : 4205
Kalan        : 795
Batch        : 159
Checkpoint   : D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\annotations\additional_5000_2026\checkpoints\reuters_gemini_checkpoint.csv
[1/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,210/5,000
[2/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,215/5,000
[3/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,220/5,000
[4/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,225/5,000
[5/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,230/5,000
[6/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,235/5,000
[7/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,240/5,000
[8/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,245/5,000
[9/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,250/5,000
[10/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,255/5,000
[11/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,260/5,000
[12/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,265/5,000
[13/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,270/5,000
[14/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,275/5,000
[15/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,280/5,000
[16/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,285/5,000
[17/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,290/5,000
[18/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,295/5,000
[19/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,300/5,000
[20/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,305/5,000
[21/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,310/5,000
[22/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,315/5,000
[23/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,320/5,000
[24/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,325/5,000
[25/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,330/5,000
[26/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,335/5,000
[27/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,340/5,000
[28/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,345/5,000
[29/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,350/5,000
[30/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,355/5,000
[31/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,360/5,000
[32/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,365/5,000
[33/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,370/5,000
[34/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,375/5,000
[35/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,380/5,000
[36/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,385/5,000
[37/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,390/5,000
[38/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,395/5,000
[39/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,400/5,000
[40/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,405/5,000
[41/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,410/5,000
[42/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,415/5,000
[43/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,420/5,000
[44/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,425/5,000
[45/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,430/5,000
[46/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,435/5,000
[47/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,440/5,000
[48/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,445/5,000
[49/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,450/5,000
[50/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,455/5,000
[51/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,460/5,000
[52/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,465/5,000
[53/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,470/5,000
[54/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,475/5,000
[55/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,480/5,000
[56/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,485/5,000
[57/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,490/5,000
[58/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,495/5,000
[59/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,500/5,000
[60/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,505/5,000
[61/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,510/5,000
[62/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,515/5,000
[63/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,520/5,000
[64/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,525/5,000
[65/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,530/5,000
[66/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,535/5,000
[67/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,540/5,000
[68/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,545/5,000
[69/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,550/5,000
[70/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,555/5,000
[71/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,560/5,000
[72/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,565/5,000
[73/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,570/5,000
[74/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,575/5,000
[75/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,580/5,000
[76/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,585/5,000
[77/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,590/5,000
[78/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,595/5,000
[79/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,600/5,000
[80/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,605/5,000
[81/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,610/5,000
[82/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,615/5,000
[83/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,620/5,000
[84/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,625/5,000
[85/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,630/5,000
[86/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,635/5,000
[87/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,640/5,000
[88/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,645/5,000
[89/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,650/5,000
[90/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,655/5,000
[91/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,660/5,000
[92/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,665/5,000
[93/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,670/5,000
[94/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,675/5,000
[95/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,680/5,000
[96/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,685/5,000
[97/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,690/5,000
[98/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,695/5,000
[99/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,700/5,000
[100/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,705/5,000
[101/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,710/5,000
[102/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,715/5,000
[103/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,720/5,000
[104/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,725/5,000
[105/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,730/5,000
[106/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,735/5,000
[107/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,740/5,000
[108/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,745/5,000
[109/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,750/5,000
[110/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,755/5,000
[111/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,760/5,000
[112/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,765/5,000
[113/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,770/5,000
[114/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,775/5,000
[115/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,780/5,000
[116/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,785/5,000
[117/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,790/5,000
[118/159] Reuters | gemini | 5 kayıt
⚠️ Gemini hata | Retry 1/8 | 5s
Geçersiz label: 'mixed'
  ✅ checkpoint | 4,795/5,000
[119/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,800/5,000
[120/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,805/5,000
[121/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,810/5,000
[122/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,815/5,000
[123/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,820/5,000
[124/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,825/5,000
[125/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,830/5,000
[126/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,835/5,000
[127/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,840/5,000
[128/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,845/5,000
[129/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,850/5,000
[130/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,855/5,000
[131/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,860/5,000
[132/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,865/5,000
[133/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,870/5,000
[134/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,875/5,000
[135/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,880/5,000
[136/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,885/5,000
[137/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,890/5,000
[138/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,895/5,000
[139/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,900/5,000
[140/159] Reuters | gemini | 5 kayıt
⚠️ Gemini hata | Retry 1/8 | 5s
Beklenen 5, gelen 4
  ✅ checkpoint | 4,905/5,000
[141/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,910/5,000
[142/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,915/5,000
[143/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,920/5,000
[144/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,925/5,000
[145/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,930/5,000
[146/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,935/5,000
[147/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,940/5,000
[148/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,945/5,000
[149/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,950/5,000
[150/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,955/5,000
[151/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,960/5,000
[152/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,965/5,000
[153/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,970/5,000
[154/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,975/5,000
[155/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,980/5,000
[156/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,985/5,000
[157/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,990/5,000
[158/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 4,995/5,000
[159/159] Reuters | gemini | 5 kayıt
  ✅ checkpoint | 5,000/5,000
✅ Reuters tamam.

## 18. S&P500 — 5.000 ChatGPT + Gemini

In [21]:
sp500_chatgpt = run_provider(
    sp500_selected,
    "SP500",
    "chatgpt",
    ask_chatgpt_batch,
    OPENAI_REQUEST_INTERVAL
)

sp500_final = run_provider(
    sp500_chatgpt,
    "SP500",
    "gemini",
    ask_gemini_batch,
    GEMINI_REQUEST_INTERVAL
)

print("✅ S&P500 tamam.")

##############################################################################################################
CHATGPT | SP500
##############################################################################################################
Toplam       : 5000
Checkpoint   : 0
Kalan        : 5000
Batch        : 1000
Checkpoint   : D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\annotations\additional_5000_2026\checkpoints\sp500_chatgpt_checkpoint.csv
[1/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 5/5,000
[2/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 10/5,000
[3/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 15/5,000
[4/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 20/5,000
[5/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 25/5,000
[6/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 30/5,000
[7/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 35/5,000
[8/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 40/5,000
[9/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 45/5,000
[10/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 50/5,000
[11/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 55/5,000
[12/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 60/5,000
[13/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 65/5,000
[14/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 70/5,000
[15/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 75/5,000
[16/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 80/5,000
[17/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 85/5,000
[18/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 90/5,000
[19/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 95/5,000
[20/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 100/5,000
[21/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 105/5,000
[22/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 110/5,000
[23/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 115/5,000
[24/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 120/5,000
[25/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 125/5,000
[26/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 130/5,000
[27/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 135/5,000
[28/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 140/5,000
[29/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 145/5,000
[30/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 150/5,000
[31/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 155/5,000
[32/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 160/5,000
[33/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 165/5,000
[34/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 170/5,000
[35/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 175/5,000
[36/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 180/5,000
[37/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 185/5,000
[38/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 190/5,000
[39/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 195/5,000
[40/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 200/5,000
[41/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 205/5,000
[42/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 210/5,000
[43/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 215/5,000
[44/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 220/5,000
[45/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 225/5,000
[46/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 230/5,000
[47/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 235/5,000
[48/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 240/5,000
[49/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 245/5,000
[50/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 250/5,000
[51/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 255/5,000
[52/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 260/5,000
[53/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 265/5,000
[54/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 270/5,000
[55/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 275/5,000
[56/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 280/5,000
[57/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 285/5,000
[58/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 290/5,000
[59/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 295/5,000
[60/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 300/5,000
[61/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 305/5,000
[62/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 310/5,000
[63/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 315/5,000
[64/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 320/5,000
[65/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 325/5,000
[66/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 330/5,000
[67/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 335/5,000
[68/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 340/5,000
[69/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 345/5,000
[70/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 350/5,000
[71/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 355/5,000
[72/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 360/5,000
[73/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 365/5,000
[74/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 370/5,000
[75/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 375/5,000
[76/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 380/5,000
[77/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 385/5,000
[78/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 390/5,000
[79/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 395/5,000
[80/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 400/5,000
[81/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 405/5,000
[82/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 410/5,000
[83/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 415/5,000
[84/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 420/5,000
[85/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 425/5,000
[86/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 430/5,000
[87/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 435/5,000
[88/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 440/5,000
[89/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 445/5,000
[90/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 450/5,000
[91/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 455/5,000
[92/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 460/5,000
[93/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 465/5,000
[94/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 470/5,000
[95/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 475/5,000
[96/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 480/5,000
[97/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 485/5,000
[98/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 490/5,000
[99/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 495/5,000
[100/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 500/5,000
[101/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 505/5,000
[102/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 510/5,000
[103/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 515/5,000
[104/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 520/5,000
[105/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 525/5,000
[106/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 530/5,000
[107/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 535/5,000
[108/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 540/5,000
[109/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 545/5,000
[110/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 550/5,000
[111/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 555/5,000
[112/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 560/5,000
[113/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 565/5,000
[114/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 570/5,000
[115/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 575/5,000
[116/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 580/5,000
[117/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 585/5,000
[118/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 590/5,000
[119/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 595/5,000
[120/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 600/5,000
[121/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 605/5,000
[122/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 610/5,000
[123/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 615/5,000
[124/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 620/5,000
[125/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 625/5,000
[126/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 630/5,000
[127/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 635/5,000
[128/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 640/5,000
[129/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 645/5,000
[130/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 650/5,000
[131/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 655/5,000
[132/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 660/5,000
[133/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 665/5,000
[134/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 670/5,000
[135/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 675/5,000
[136/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 680/5,000
[137/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 685/5,000
[138/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 690/5,000
[139/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 695/5,000
[140/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 700/5,000
[141/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 705/5,000
[142/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 710/5,000
[143/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 715/5,000
[144/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 720/5,000
[145/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 725/5,000
[146/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 730/5,000
[147/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 735/5,000
[148/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 740/5,000
[149/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 745/5,000
[150/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 750/5,000
[151/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 755/5,000
[152/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 760/5,000
[153/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 765/5,000
[154/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 770/5,000
[155/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 775/5,000
[156/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 780/5,000
[157/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 785/5,000
[158/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 790/5,000
[159/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 795/5,000
[160/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 800/5,000
[161/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 805/5,000
[162/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 810/5,000
[163/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 815/5,000
[164/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 820/5,000
[165/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 825/5,000
[166/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 830/5,000
[167/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 835/5,000
[168/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 840/5,000
[169/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 845/5,000
[170/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 850/5,000
[171/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 855/5,000
[172/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 860/5,000
[173/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 865/5,000
[174/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 870/5,000
[175/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 875/5,000
[176/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 880/5,000
[177/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 885/5,000
[178/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 890/5,000
[179/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 895/5,000
[180/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 900/5,000
[181/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 905/5,000
[182/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 910/5,000
[183/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 915/5,000
[184/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 920/5,000
[185/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 925/5,000
[186/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 930/5,000
[187/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 935/5,000
[188/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 940/5,000
[189/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 945/5,000
[190/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 950/5,000
[191/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 955/5,000
[192/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 960/5,000
[193/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 965/5,000
[194/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 970/5,000
[195/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 975/5,000
[196/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 980/5,000
[197/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 985/5,000
[198/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 990/5,000
[199/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 995/5,000
[200/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,000/5,000
[201/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,005/5,000
[202/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,010/5,000
[203/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,015/5,000
[204/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,020/5,000
[205/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,025/5,000
[206/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,030/5,000
[207/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,035/5,000
[208/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,040/5,000
[209/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,045/5,000
[210/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,050/5,000
[211/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,055/5,000
[212/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,060/5,000
[213/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,065/5,000
[214/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,070/5,000
[215/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,075/5,000
[216/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,080/5,000
[217/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,085/5,000
[218/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,090/5,000
[219/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,095/5,000
[220/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,100/5,000
[221/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,105/5,000
[222/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,110/5,000
[223/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,115/5,000
[224/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,120/5,000
[225/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,125/5,000
[226/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,130/5,000
[227/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,135/5,000
[228/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,140/5,000
[229/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,145/5,000
[230/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,150/5,000
[231/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,155/5,000
[232/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,160/5,000
[233/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,165/5,000
[234/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,170/5,000
[235/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,175/5,000
[236/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,180/5,000
[237/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,185/5,000
[238/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,190/5,000
[239/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,195/5,000
[240/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,200/5,000
[241/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,205/5,000
[242/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,210/5,000
[243/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,215/5,000
[244/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,220/5,000
[245/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,225/5,000
[246/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,230/5,000
[247/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,235/5,000
[248/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,240/5,000
[249/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,245/5,000
[250/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,250/5,000
[251/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,255/5,000
[252/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,260/5,000
[253/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,265/5,000
[254/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,270/5,000
[255/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,275/5,000
[256/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,280/5,000
[257/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,285/5,000
[258/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,290/5,000
[259/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,295/5,000
[260/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,300/5,000
[261/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,305/5,000
[262/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,310/5,000
[263/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,315/5,000
[264/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,320/5,000
[265/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,325/5,000
[266/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,330/5,000
[267/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,335/5,000
[268/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,340/5,000
[269/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,345/5,000
[270/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,350/5,000
[271/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,355/5,000
[272/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,360/5,000
[273/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,365/5,000
[274/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,370/5,000
[275/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,375/5,000
[276/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,380/5,000
[277/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,385/5,000
[278/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,390/5,000
[279/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,395/5,000
[280/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,400/5,000
[281/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,405/5,000
[282/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,410/5,000
[283/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,415/5,000
[284/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,420/5,000
[285/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,425/5,000
[286/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,430/5,000
[287/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,435/5,000
[288/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,440/5,000
[289/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,445/5,000
[290/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,450/5,000
[291/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,455/5,000
[292/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,460/5,000
[293/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,465/5,000
[294/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,470/5,000
[295/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,475/5,000
[296/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,480/5,000
[297/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,485/5,000
[298/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,490/5,000
[299/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,495/5,000
[300/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,500/5,000
[301/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,505/5,000
[302/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,510/5,000
[303/1000] SP500 | chatgpt | 5 kayıt
  ✅ checkpoint | 1,515/5,000
[304/1000] SP500 | chatgpt | 5 kayıt

## 19. ChatGPT/Gemini agreement ve consensus

In [22]:
def add_consensus(df):
    df = df.copy()

    df["chatgpt_label"] = (
        df["chatgpt_label"]
        .astype("string")
        .str.lower()
        .str.strip()
    )

    df["gemini_label"] = (
        df["gemini_label"]
        .astype("string")
        .str.lower()
        .str.strip()
    )

    valid = (
        df["chatgpt_label"].isin(VALID_LABELS)
        &
        df["gemini_label"].isin(VALID_LABELS)
    )

    df["llm_agreement"] = False

    df.loc[
        valid,
        "llm_agreement"
    ] = (
        df.loc[
            valid,
            "chatgpt_label"
        ]
        ==
        df.loc[
            valid,
            "gemini_label"
        ]
    )

    df["consensus_label"] = pd.NA

    df.loc[
        df["llm_agreement"],
        "consensus_label"
    ] = df.loc[
        df["llm_agreement"],
        "chatgpt_label"
    ]

    return df


reuters_final = add_consensus(
    reuters_final
)

sp500_final = add_consensus(
    sp500_final
)

print(
    "Reuters agreement:",
    reuters_final["llm_agreement"].mean()
)

print(
    "S&P500 agreement:",
    sp500_final["llm_agreement"].mean()
)

Reuters agreement: 0.7696
S&P500 agreement: 0.902

## 20. Final dosyaları kaydet

In [23]:
REUTERS_ALL_PATH = (
    FINAL_DIR / "reuters_additional_5000_all.csv"
)

REUTERS_CONSENSUS_PATH = (
    FINAL_DIR / "reuters_additional_5000_consensus.csv"
)

SP500_ALL_PATH = (
    FINAL_DIR / "sp500_additional_5000_all.csv"
)

SP500_CONSENSUS_PATH = (
    FINAL_DIR / "sp500_additional_5000_consensus.csv"
)

COMBINED_ALL_PATH = (
    FINAL_DIR / "additional_5000_each_combined_all.csv"
)

COMBINED_CONSENSUS_PATH = (
    FINAL_DIR / "additional_5000_each_combined_consensus.csv"
)


reuters_final.to_csv(
    REUTERS_ALL_PATH,
    index=False,
    encoding="utf-8-sig"
)

reuters_final[
    reuters_final["llm_agreement"]
].to_csv(
    REUTERS_CONSENSUS_PATH,
    index=False,
    encoding="utf-8-sig"
)

sp500_final.to_csv(
    SP500_ALL_PATH,
    index=False,
    encoding="utf-8-sig"
)

sp500_final[
    sp500_final["llm_agreement"]
].to_csv(
    SP500_CONSENSUS_PATH,
    index=False,
    encoding="utf-8-sig"
)

combined_all = pd.concat(
    [
        reuters_final,
        sp500_final
    ],
    ignore_index=True
)

combined_consensus = combined_all[
    combined_all["llm_agreement"]
].copy()

combined_all.to_csv(
    COMBINED_ALL_PATH,
    index=False,
    encoding="utf-8-sig"
)

combined_consensus.to_csv(
    COMBINED_CONSENSUS_PATH,
    index=False,
    encoding="utf-8-sig"
)

print("✅ Reuters all       :", REUTERS_ALL_PATH)
print("✅ Reuters consensus :", REUTERS_CONSENSUS_PATH)
print("✅ S&P500 all        :", SP500_ALL_PATH)
print("✅ S&P500 consensus  :", SP500_CONSENSUS_PATH)
print("✅ Combined all      :", COMBINED_ALL_PATH)
print("✅ Combined consensus:", COMBINED_CONSENSUS_PATH)

✅ Reuters all       : D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\annotations\additional_5000_2026\final\reuters_additional_5000_all.csv
✅ Reuters consensus : D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\annotations\additional_5000_2026\final\reuters_additional_5000_consensus.csv
✅ S&P500 all        : D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\annotations\additional_5000_2026\final\sp500_additional_5000_all.csv
✅ S&P500 consensus  : D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\annotations\additional_5000_2026\final\sp500_additional_5000_consensus.csv
✅ Combined all      : D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\annotations\additional_5000_2026\final\additional_5000_each_combined_all.csv
✅ Combined consensus: D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\annotations\additional_5000_2026\final\additional_5000_each_combined_consensus.csv

## 21. Cohen's Kappa — yeni 5.000'er kayıt

In [24]:
def calculate_kappa(
    df,
    dataset_name
):
    data = df[
        df["chatgpt_label"].isin(VALID_LABELS)
        &
        df["gemini_label"].isin(VALID_LABELS)
    ].copy()

    agreement = (
        data["chatgpt_label"]
        ==
        data["gemini_label"]
    ).mean()

    kappa = cohen_kappa_score(
        data["chatgpt_label"],
        data["gemini_label"],
        labels=VALID_LABELS
    )

    print("\n" + "=" * 100)
    print(dataset_name)
    print("=" * 100)
    print("Toplam kayıt   :", len(df))
    print("Karşılaştırılan:", len(data))
    print(
        f"Agreement      : {agreement:.4f} "
        f"({agreement:.2%})"
    )
    print(
        f"Cohen's Kappa  : {kappa:.4f}"
    )

    matrix = pd.crosstab(
        data["chatgpt_label"],
        data["gemini_label"],
        rownames=["ChatGPT"],
        colnames=["Gemini"]
    ).reindex(
        index=VALID_LABELS,
        columns=VALID_LABELS,
        fill_value=0
    )

    print("\nConfusion Matrix:")
    display(matrix)

    return {
        "dataset": dataset_name,
        "n": len(data),
        "agreement": agreement,
        "kappa": kappa,
        "matrix": matrix
    }


reuters_kappa = calculate_kappa(
    reuters_final,
    "REUTERS - ADDITIONAL 5,000"
)

sp500_kappa = calculate_kappa(
    sp500_final,
    "S&P500 - ADDITIONAL 5,000"
)

====================================================================================================
REUTERS - ADDITIONAL 5,000
====================================================================================================
Toplam kayıt   : 5000
Karşılaştırılan: 5000
Agreement      : 0.7696 (76.96%)
Cohen's Kappa  : 0.6522

Confusion Matrix:

Gemini    negative  neutral  positive
ChatGPT
negative      1780      610        51
neutral         45      936       126
positive        13      307      1132

====================================================================================================
S&P500 - ADDITIONAL 5,000
====================================================================================================
Toplam kayıt   : 5000
Karşılaştırılan: 5000
Agreement      : 0.9020 (90.20%)
Cohen's Kappa  : 0.8465

Confusion Matrix:

Gemini    negative  neutral  positive
ChatGPT
negative      1022      211         9
neutral         44     2095        80
positive         5      141      1393

## 22. Final özet

In [25]:
summary = pd.DataFrame([
    {
        "dataset": "Reuters",
        "selected": len(reuters_final),
        "consensus": int(
            reuters_final["llm_agreement"].sum()
        ),
        "agreement": reuters_final["llm_agreement"].mean()
    },
    {
        "dataset": "SP500",
        "selected": len(sp500_final),
        "consensus": int(
            sp500_final["llm_agreement"].sum()
        ),
        "agreement": sp500_final["llm_agreement"].mean()
    }
])

display(summary)

kappa_summary = pd.DataFrame([
    {
        "dataset": reuters_kappa["dataset"],
        "n": reuters_kappa["n"],
        "agreement": reuters_kappa["agreement"],
        "kappa": reuters_kappa["kappa"]
    },
    {
        "dataset": sp500_kappa["dataset"],
        "n": sp500_kappa["n"],
        "agreement": sp500_kappa["agreement"],
        "kappa": sp500_kappa["kappa"]
    }
])

display(kappa_summary)

summary.to_csv(
    RESULT_DIR / "additional_5000_summary.csv",
    index=False,
    encoding="utf-8-sig"
)

kappa_summary.to_csv(
    RESULT_DIR / "additional_5000_kappa_summary.csv",
    index=False,
    encoding="utf-8-sig"
)

print("✅ Sonuç klasörü:", RESULT_DIR)

   dataset  selected  consensus  agreement
0  Reuters      5000       3848     0.7696
1    SP500      5000       4510     0.9020

                      dataset     n  agreement     kappa
0  REUTERS - ADDITIONAL 5,000  5000     0.7696  0.652205
1   S&P500 - ADDITIONAL 5,000  5000     0.9020  0.846483

✅ Sonuç klasörü: D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\annotations\additional_5000_2026\results