# 21 - Twitter Financial News + Financial PhraseBank yeniden etiketleme

Bu notebook iki veri grubunu yeniden etiketler:

1. `Twitter Financial News Sentiment` — `sent_train.csv` + `sent_valid.csv`
2. `Financial PhraseBank` — 50%, 66%, 75% ve 100% agreement konfigürasyonları

Her kayıt için:
- `human_label` = veri setinin mevcut/orijinal referans etiketi
- `chatgpt_label` = OpenAI
- `gemini_label` = Gemini

Son bölümde üç çift için Cohen's Kappa hesaplanır:
- Human ↔ ChatGPT
- Human ↔ Gemini
- ChatGPT ↔ Gemini

PhraseBank konfigürasyonları aynı cümleleri kısmen paylaşabildiği için API çağrısını azaltmak amacıyla PhraseBank içinde aynı normalize edilmiş metin yalnızca bir kez LLM'e gönderilir; sonuç ilgili konfigürasyonlara geri dağıtılır.

API anahtarları notebook'a yazılmaz. Environment variable kullanılır.

In [50]:
%pip install -q -U openai google-genai pandas scikit-learn statsmodels

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

## 1. Import ve ayarlar

In [51]:
from pathlib import Path
import os
import io
import json
import re
import time
import zipfile
import urllib.request
from getpass import getpass

import pandas as pd
import numpy as np

from IPython.display import display
from sklearn.metrics import cohen_kappa_score, confusion_matrix

pd.set_option("display.max_colwidth", 180)
pd.set_option("display.max_columns", 100)
pd.set_option("display.width", 220)

VALID_LABELS = ["negative", "neutral", "positive"]

TWITTER_HF_BASE = "hf://datasets/zeroshot/twitter-financial-news-sentiment/"
PHRASEBANK_ZIP_URL = (
    "https://huggingface.co/datasets/takala/financial_phrasebank/"
    "resolve/main/data/FinancialPhraseBank-v1.0.zip"
)

# Tüm PhraseBank konfigürasyonlarını indir ve veri olarak tut.
PHRASEBANK_CONFIGS = {
    "50agree": "FinancialPhraseBank-v1.0/Sentences_50Agree.txt",
    "66agree": "FinancialPhraseBank-v1.0/Sentences_66Agree.txt",
    "75agree": "FinancialPhraseBank-v1.0/Sentences_75Agree.txt",
    "allagree": "FinancialPhraseBank-v1.0/Sentences_AllAgree.txt",
}

# API batch ayarları
BATCH_SIZE = 5

# Gemini tarafında 18 numaralı notebooktaki çalışma mantığını koruyoruz.
GEMINI_REQUEST_INTERVAL = 5.0

# OpenAI için paid API kullanıldığı için daha kısa bekleme.
OPENAI_REQUEST_INTERVAL = 0.5

# Retry üst sınırı
MAX_RETRIES = 8

# Ana model adları
OPENAI_MODEL = "gpt-5.6-luna"
GEMINI_MODEL = "gemini-3.5-flash-lite"

# Annotation çıktılarını projenin db/annotations altında tut.
PROJECT_DIR = Path(
    r"D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis"
)
DATA_DIR = PROJECT_DIR / "db"

OUTPUT_DIR = DATA_DIR / "annotations" / "reannotation_21"
CHECKPOINT_DIR = OUTPUT_DIR / "checkpoints"
FINAL_DIR = OUTPUT_DIR / "final"
RESULT_DIR = OUTPUT_DIR / "results"

for p in [OUTPUT_DIR, CHECKPOINT_DIR, FINAL_DIR, RESULT_DIR]:
    p.mkdir(parents=True, exist_ok=True)

print("PROJECT_DIR :", PROJECT_DIR)
print("DATA_DIR    :", DATA_DIR)
print("OUTPUT_DIR  :", OUTPUT_DIR)
print("BATCH_SIZE  :", BATCH_SIZE)
print("OpenAI      :", OPENAI_MODEL)
print("Gemini      :", GEMINI_MODEL)

PROJECT_DIR : D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis
DATA_DIR    : D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db
OUTPUT_DIR  : D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\annotations\reannotation_21
BATCH_SIZE  : 5
OpenAI      : gpt-5.6-luna
Gemini      : gemini-3.5-flash-lite

## 2. API anahtarlarını yükle

19 numaralı notebookta anahtar notebook içine yazılmıştı. Bu notebookta anahtarları tekrar yazmıyoruz.

Windows environment variable:
- `OPENAI_API_KEY`
- `GEMINI_API_KEY`

Environment variable yoksa notebook güvenli bir şekilde `getpass()` ile sorar.

In [52]:
# -----------------------------
# OpenAI
# -----------------------------
OPENAI_API_KEY = "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";


if not OPENAI_API_KEY:
    OPENAI_API_KEY = getpass("OPENAI_API_KEY girin: ").strip()

if not OPENAI_API_KEY:
    raise RuntimeError("OPENAI_API_KEY bulunamadı.")

# -----------------------------
# Gemini
# -----------------------------
GEMINI_API_KEY = "AQ.Ab8RN6IVVX_2kWKkap7nUDkXllD4tl9j5KY4E5s7FF86rZ3huA";


if not GEMINI_API_KEY:
    GEMINI_API_KEY = getpass("GEMINI_API_KEY girin: ").strip()

if not GEMINI_API_KEY:
    raise RuntimeError("GEMINI_API_KEY bulunamadı.")

print("OpenAI key: bulundu")
print("Gemini key : bulundu")

OpenAI key: bulundu
Gemini key : bulundu

## 3. API client'larını oluştur

In [53]:
from openai import OpenAI
from google import genai
from google.genai import types

openai_client = OpenAI(api_key=OPENAI_API_KEY)

gemini_client = genai.Client(
    api_key=GEMINI_API_KEY,
    http_options=types.HttpOptions(timeout=60000),
)

print("✅ OpenAI client hazır")
print("✅ Gemini client hazır")

✅ OpenAI client hazır
✅ Gemini client hazır

## 4. Twitter Financial News Sentiment'i indir

Hugging Face kaynağındaki `sent_train.csv` ve `sent_valid.csv` birlikte alınır.

Kaynak label dönüşümü:
- `0 -> negative`
- `1 -> positive`
- `2 -> neutral`

In [54]:
twitter_train = pd.read_csv(
    TWITTER_HF_BASE + "sent_train.csv"
)

twitter_valid = pd.read_csv(
    TWITTER_HF_BASE + "sent_valid.csv"
)

twitter_train = twitter_train.copy()
twitter_valid = twitter_valid.copy()

twitter_train["source_original_split"] = "train"
twitter_valid["source_original_split"] = "validation"

twitter_df = pd.concat(
    [twitter_train, twitter_valid],
    ignore_index=True
)

twitter_label_map = {
    0: "negative",
    1: "positive",
    2: "neutral",
    "0": "negative",
    "1": "positive",
    "2": "neutral",
}

twitter_df["human_label"] = (
    twitter_df["label"]
    .map(twitter_label_map)
)

twitter_df["text"] = (
    twitter_df["text"]
    .astype(str)
    .str.strip()
)

twitter_df = twitter_df[
    twitter_df["text"].ne("")
].copy()

twitter_df["dataset"] = "TwitterFinancialNewsSentiment"
twitter_df["config"] = "full"
twitter_df["source_index"] = np.arange(len(twitter_df))

print("=" * 100)
print("TWITTER FINANCIAL NEWS SENTIMENT")
print("=" * 100)
print("Train       :", len(twitter_train))
print("Validation  :", len(twitter_valid))
print("Toplam      :", len(twitter_df))
print("\nHuman label:")
print(twitter_df["human_label"].value_counts())
display(twitter_df[["text", "label", "human_label", "source_original_split"]].head())

====================================================================================================
TWITTER FINANCIAL NEWS SENTIMENT
====================================================================================================
Train       : 9543
Validation  : 2388
Toplam      : 11931

Human label:
human_label
neutral     7744
positive    2398
negative    1789
Name: count, dtype: int64

                                                                                                     text  label human_label source_original_split
0                           $BYND - JPMorgan reels in expectations on Beyond Meat https://t.co/bd0xbFGjkT      0    negative                 train
1  $CCL $RCL - Nomura points to bookings weakness at Carnival and Royal Caribbean https://t.co/yGjpT2ReD3      0    negative                 train
2          $CX - Cemex cut at Credit Suisse, J.P. Morgan on weak building outlook https://t.co/KN1g4AWFIb      0    negative                 train
3                                             $ESS: BTIG Research cuts to Neutral https://t.co/MCyfTsXc2N      0    negative                 train
4                                 $FNKO - Funko slides after Piper Jaffray PT cut https://t.co/z37IJmCQzB      0    negative                 train

## 5. Financial PhraseBank'i ZIP olarak indir ve dört konfigürasyonu oku

`datasets` loader scripti yeni sürümlerde çalışmadığı için burada doğrudan veri ZIP'i okunuyor.

In [55]:
print("Financial PhraseBank ZIP indiriliyor...")

with urllib.request.urlopen(PHRASEBANK_ZIP_URL) as response:
    phrasebank_zip_bytes = response.read()

print(
    f"ZIP boyutu: {len(phrasebank_zip_bytes) / 1024**2:.2f} MB"
)

phrasebank_dfs = {}

with zipfile.ZipFile(io.BytesIO(phrasebank_zip_bytes)) as z:
    names = set(z.namelist())

    print("\nZIP içindeki beklenen dosyalar:")
    for config, file_name in PHRASEBANK_CONFIGS.items():
        print(config, "->", file_name, file_name in names)

    for config, file_name in PHRASEBANK_CONFIGS.items():

        rows = []

        with z.open(file_name) as f:
            for line in f:
                line = line.decode(
                    "iso-8859-1"
                ).rstrip("\r\n")

                if not line.strip():
                    continue

                text, label = line.rsplit("@", 1)

                rows.append({
                    "text": text.strip(),
                    "human_label": label.strip().lower(),
                })

        df = pd.DataFrame(rows)

        df["dataset"] = "FinancialPhraseBank"
        df["config"] = config
        df["source_index"] = np.arange(len(df))

        phrasebank_dfs[config] = df

        print(
            f"{config:10s}: {len(df):,} kayıt"
        )
        print(df["human_label"].value_counts().to_dict())

print("\n✅ PhraseBank hazır.")

Financial PhraseBank ZIP indiriliyor...
ZIP boyutu: 0.65 MB

ZIP içindeki beklenen dosyalar:
50agree -> FinancialPhraseBank-v1.0/Sentences_50Agree.txt True
66agree -> FinancialPhraseBank-v1.0/Sentences_66Agree.txt True
75agree -> FinancialPhraseBank-v1.0/Sentences_75Agree.txt True
allagree -> FinancialPhraseBank-v1.0/Sentences_AllAgree.txt True
50agree   : 4,846 kayıt
{'neutral': 2879, 'positive': 1363, 'negative': 604}
66agree   : 4,217 kayıt
{'neutral': 2535, 'positive': 1168, 'negative': 514}
75agree   : 3,453 kayıt
{'neutral': 2146, 'positive': 887, 'negative': 420}
allagree  : 2,264 kayıt
{'neutral': 1391, 'positive': 570, 'negative': 303}

✅ PhraseBank hazır.

## 6. İnsan/reference etiketlerini ve metinleri kontrol et

In [56]:
print("=" * 100)
print("LABEL KONTROLLERİ")
print("=" * 100)

print("\nTwitter geçerli label?")
print(set(twitter_df["human_label"].dropna().unique()))

for config, df in phrasebank_dfs.items():
    print(
        f"\nPhraseBank {config}:",
        sorted(df["human_label"].dropna().unique())
    )

print("\nTwitter shape:", twitter_df.shape)

for config, df in phrasebank_dfs.items():
    print(f"PhraseBank {config}: {df.shape}")

====================================================================================================
LABEL KONTROLLERİ
====================================================================================================

Twitter geçerli label?
{'neutral', 'positive', 'negative'}

PhraseBank 50agree: ['negative', 'neutral', 'positive']

PhraseBank 66agree: ['negative', 'neutral', 'positive']

PhraseBank 75agree: ['negative', 'neutral', 'positive']

PhraseBank allagree: ['negative', 'neutral', 'positive']

Twitter shape: (11931, 7)
PhraseBank 50agree: (4846, 5)
PhraseBank 66agree: (4217, 5)
PhraseBank 75agree: (3453, 5)
PhraseBank allagree: (2264, 5)

## 7. Annotation kuyruğunu oluştur

PhraseBank konfigürasyonları aynı cümlelerin alt kümelerini içerdiğinden:
- aynı normalize metin tekrar tekrar API'ye gönderilmez,
- LLM etiketi daha sonra ilgili tüm PhraseBank config satırlarına geri dağıtılır.

Aynı metin farklı human label ile bulunursa bu durum ayrıca raporlanır.

In [57]:
import math

In [58]:
def normalize_text(text):
    text = str(text)
    text = re.sub(r"\s+", " ", text).strip().lower()
    return text

twitter_queue = twitter_df[
    ["dataset", "config", "source_index", "text", "human_label"]
].copy()

twitter_queue["text_key"] = twitter_queue["text"].map(normalize_text)
twitter_queue["annotation_group"] = "twitter"

phrasebank_all = pd.concat(
    phrasebank_dfs.values(),
    ignore_index=True
)

phrasebank_all["text_key"] = phrasebank_all["text"].map(normalize_text)
phrasebank_all["annotation_group"] = "phrasebank"

# Her text sadece bir kez LLM'e gitsin.
phrasebank_conflicts = (
    phrasebank_all.groupby("text_key")["human_label"]
    .nunique()
    .reset_index(name="n_labels")
)

conflicting_text_keys = set(
    phrasebank_conflicts.loc[
        phrasebank_conflicts["n_labels"] > 1,
        "text_key"
    ]
)

print(
    "PhraseBank aynı metin için human label çelişkisi:",
    len(conflicting_text_keys)
)

if conflicting_text_keys:
    print(
        "İlk örnekler:",
        list(conflicting_text_keys)[:5]
    )

# PhraseBank benzersiz annotation queue
phrasebank_queue = (
    phrasebank_all
    .sort_values(["text_key", "config"])
    .drop_duplicates(
        subset=["text_key"],
        keep="first"
    )
    [["dataset", "config", "source_index", "text", "human_label", "text_key"]]
    .copy()
)

# Twitter'da da aynı metin birden fazla split'te geçerse tek API çağrısı:
twitter_queue_unique = (
    twitter_queue
    .sort_values(["text_key", "source_original_split"] if "source_original_split" in twitter_queue.columns else ["text_key"])
    .drop_duplicates(
        subset=["text_key"],
        keep="first"
    )
    .copy()
)

# Daha açıklayıcı ID
twitter_queue_unique["annotation_id"] = [
    f"twitter_{i:06d}"
    for i in range(len(twitter_queue_unique))
]

phrasebank_queue["annotation_id"] = [
    f"phrasebank_{i:06d}"
    for i in range(len(phrasebank_queue))
]

twitter_queue_unique["chatgpt_label"] = pd.NA
twitter_queue_unique["gemini_label"] = pd.NA

phrasebank_queue["chatgpt_label"] = pd.NA
phrasebank_queue["gemini_label"] = pd.NA

print("\n" + "=" * 100)
print("API ANNOTATION QUEUE")
print("=" * 100)
print("Twitter unique text      :", len(twitter_queue_unique))
print("PhraseBank unique text   :", len(phrasebank_queue))

total_queue = len(twitter_queue_unique) + len(phrasebank_queue)

print("Toplam benzersiz API text:", total_queue)
print("Batch size               :", BATCH_SIZE)
print(
    "ChatGPT tahmini batch:",
    math.ceil(total_queue / BATCH_SIZE)
)
print(
    "Gemini tahmini batch:",
    math.ceil(total_queue / BATCH_SIZE)
)

PhraseBank aynı metin için human label çelişkisi: 2
İlk örnekler: ['telecomworldwire-7 april 2006-tj group plc sells stake in morning digital design oy finnish it company tj group plc said on friday 7 april that it had signed an agreement on selling its shares of morning digital design oy to edita oyj .', "the group 's business is balanced by its broad portfolio of sports and presence in all major markets ."]

====================================================================================================
API ANNOTATION QUEUE
====================================================================================================
Twitter unique text      : 11924
PhraseBank unique text   : 4838
Toplam benzersiz API text: 16762
Batch size               : 5
ChatGPT tahmini batch: 3353
Gemini tahmini batch: 3353

## 8. Aynı sentiment prompt'unu iki modele de uygula

Prompt yapısı 18 numaralı Gemini notebookundaki finansal sentiment kurallarını temel alır.

In [59]:
PROMPT_TEMPLATE = """
You are an expert financial sentiment annotator.

Your task is to classify the OVERALL FINANCIAL SENTIMENT of each
financial text, sentence, or headline.

You MUST assign exactly ONE label:

- positive
- negative
- neutral

IMPORTANT:
Classify the meaning and financial implication of the WHOLE text.
Do NOT classify based on individual words.

LABEL DEFINITIONS

positive:
The text communicates an overall favorable financial or business
development, such as:
- stronger-than-expected performance
- increased profits or revenue
- successful business expansion
- improving financial outlook
- favorable market developments
- positive investor/business implications
- successful deals or developments that are beneficial to a company,
  industry, or market

negative:
The text communicates an overall unfavorable financial or business
development, such as:
- falling profits or revenue
- weaker-than-expected performance
- deteriorating outlook
- financial losses
- business problems
- negative investor/business implications
- significant risks, failures, or adverse developments

neutral:
The text is primarily factual, descriptive, procedural, or
informational and does not communicate a clearly favorable or
unfavorable financial implication.

CRITICAL RULES

1. Do NOT classify based only on positive-looking words.

For example:
"factory orders up less than expected"
should NOT automatically be positive.

The phrase "less than expected" changes the financial meaning.

2. Do NOT classify based only on negative-looking words.

For example:
"airlines on rocky road, but recovery remains intact"
contains negative wording, but the overall message is mixed.
If neither direction clearly dominates, classify it as neutral.

3. Consider comparisons with expectations.

Examples:
"profit rises more than expected"
=> positive

"profit rises less than expected"
=> negative

"orders fall less than expected"
=> positive or neutral depending on
the overall financial implication.

"orders fall more than expected"
=> negative

4. If the text contains BOTH positive and negative information:
- use the MAIN financial implication;
- if one direction clearly dominates, use that direction;
- if the information is genuinely balanced/conflicting without
  a clearly dominant direction, use neutral.

NEVER return "mixed".

5. Words such as "up", "rise", "growth", "help", "recovery"
do NOT automatically mean positive.

Words such as "fall", "drop", "weak", "worry", "rocky"
do NOT automatically mean negative.

6. Neutral does NOT mean "I am uncertain".
Use neutral when the text itself is informational or balanced.

7. Do not use outside knowledge about companies or events.
Classify ONLY what can reasonably be inferred from the provided text.

8. Preserve input order.

OUTPUT FORMAT

Return JSON only:

{{"labels": ["positive", "neutral", "negative"]}}

The labels array MUST contain exactly one label for every input item.

Allowed labels:
positive
negative
neutral

NEVER return:
mixed
both
uncertain
unknown
or any other label.

ITEMS:
{items}
"""

def build_prompt(texts):
    items = [
        {"index": i, "text": str(text)}
        for i, text in enumerate(texts)
    ]
    return PROMPT_TEMPLATE.format(
        items=json.dumps(items, ensure_ascii=False)
    )

## 9. Label parser ve retry yardımcıları

In [60]:
def normalize_label(value):
    value = str(value).strip().lower()

    if value not in VALID_LABELS:
        raise ValueError(f"Geçersiz label: {value!r}")

    return value


def parse_labels_json(raw, expected_count):
    if not raw:
        raise RuntimeError("Boş model cevabı.")

    try:
        data = json.loads(raw)
    except json.JSONDecodeError as e:
        raise RuntimeError(
            f"Geçerli JSON alınamadı: {raw!r}"
        ) from e

    labels = data.get("labels")

    if not isinstance(labels, list):
        raise RuntimeError(
            f"'labels' listesi bulunamadı: {data!r}"
        )

    if len(labels) != expected_count:
        raise RuntimeError(
            f"Beklenen {expected_count} label, "
            f"gelen {len(labels)}"
        )

    return [normalize_label(x) for x in labels]


def extract_retry_delay(error):
    message = str(error)

    patterns = [
        r"retryDelay['\"]?\s*[:=]\s*['\"]?(\d+(?:\.\d+)?)s",
        r"retry in\s+(\d+(?:\.\d+)?)s",
    ]

    for pattern in patterns:
        match = re.search(
            pattern,
            message,
            flags=re.IGNORECASE
        )
        if match:
            return float(match.group(1))

    return None


def retry_sleep(retry_no, error, provider):
    base = min(5 * (2 ** (retry_no - 1)), 120)
    suggested = extract_retry_delay(error)

    wait_seconds = max(
        base,
        suggested if suggested is not None else 0
    )

    print(
        f"⚠️ {provider} hata | "
        f"Retry #{retry_no} | "
        f"{wait_seconds:.1f}s bekleme"
    )
    print("   ", str(error)[:500])

    time.sleep(wait_seconds)

## 10. ChatGPT batch fonksiyonu

Responses API + JSON schema kullanılır.

In [61]:
def ask_chatgpt_batch(texts):
    prompt = build_prompt(texts)

    for retry_no in range(1, MAX_RETRIES + 1):
        try:
            response = openai_client.responses.create(
                model=OPENAI_MODEL,
                input=prompt,
                text={
                    "format": {
                        "type": "json_schema",
                        "name": "financial_sentiment_labels",
                        "strict": True,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "labels": {
                                    "type": "array",
                                    "items": {
                                        "type": "string",
                                        "enum": VALID_LABELS
                                    }
                                }
                            },
                            "required": ["labels"],
                            "additionalProperties": False
                        }
                    }
                }
            )

            return parse_labels_json(
                response.output_text,
                expected_count=len(texts)
            )

        except KeyboardInterrupt:
            raise

        except Exception as e:

            if retry_no >= MAX_RETRIES:
                raise RuntimeError(
                    f"ChatGPT batch {MAX_RETRIES} retry sonrası başarısız."
                ) from e

            retry_sleep(
                retry_no,
                e,
                "ChatGPT"
            )

## 11. Gemini batch fonksiyonu

In [62]:
def ask_gemini_batch(texts):
    prompt = build_prompt(texts)

    for retry_no in range(1, MAX_RETRIES + 1):
        try:

            response = gemini_client.models.generate_content(
                model=GEMINI_MODEL,
                contents=prompt,
                config=types.GenerateContentConfig(
                    temperature=0.0,
                    response_mime_type="application/json",
                ),
            )

            raw = getattr(response, "text", None)

            return parse_labels_json(
                raw,
                expected_count=len(texts)
            )

        except KeyboardInterrupt:
            raise

        except Exception as e:

            if retry_no >= MAX_RETRIES:
                raise RuntimeError(
                    f"Gemini batch {MAX_RETRIES} retry sonrası başarısız."
                ) from e

            retry_sleep(
                retry_no,
                e,
                "Gemini"
            )

## 12. API test — önce yalnızca 1 örnek

Bu hücre başarılı olmadan büyük etiketleme başlamaz.

In [63]:
TEST_TEXT = (
    "Revenue for the quarter increased by 15% compared to last year."
)

print("=" * 100)
print("CHATGPT TEST")
print("=" * 100)

chatgpt_test = ask_chatgpt_batch([TEST_TEXT])
print("ChatGPT:", chatgpt_test)

print("\n" + "=" * 100)
print("GEMINI TEST")
print("=" * 100)

gemini_test = ask_gemini_batch([TEST_TEXT])
print("Gemini:", gemini_test)

print("\n✅ İki API de test verdi.")

====================================================================================================
CHATGPT TEST
====================================================================================================
ChatGPT: ['positive']

====================================================================================================
GEMINI TEST
====================================================================================================
Gemini: ['positive']

✅ İki API de test verdi.

## 13. Checkpoint yardımcıları

Her başarılı batch anında diske yazılır. Notebook kesilirse daha önce tamamlanan kayıtlar tekrar gönderilmez.

In [64]:
def checkpoint_path(provider, dataset_name):
    safe_dataset = dataset_name.lower().replace(" ", "_")
    return (
        CHECKPOINT_DIR
        / f"{safe_dataset}_{provider}_checkpoint.csv"
    )


def load_checkpoint(path):
    path = Path(path)

    if not path.exists() or path.stat().st_size == 0:
        return pd.DataFrame(
            columns=[
                "annotation_id",
                "text_key",
                "text",
                "label",
            ]
        )

    try:
        df = pd.read_csv(
            path,
            encoding="utf-8-sig",
            dtype=str
        )
    except pd.errors.EmptyDataError:
        return pd.DataFrame(
            columns=[
                "annotation_id",
                "text_key",
                "text",
                "label",
            ]
        )

    required = {
        "annotation_id",
        "text_key",
        "text",
        "label",
    }

    missing = required - set(df.columns)

    if missing:
        raise ValueError(
            f"Checkpoint kolonları eksik: {missing}"
        )

    df["label"] = (
        df["label"]
        .astype("string")
        .str.strip()
        .str.lower()
    )

    df = df[
        df["label"].isin(VALID_LABELS)
    ].copy()

    df = (
        df.drop_duplicates(
            subset=["annotation_id"],
            keep="last"
        )
        .reset_index(drop=True)
    )

    return df


def append_checkpoint(path, rows):
    path = Path(path)

    batch_df = pd.DataFrame(rows)

    if batch_df.empty:
        return

    write_header = not path.exists()

    batch_df.to_csv(
        path,
        mode="a",
        header=write_header,
        index=False,
        encoding="utf-8-sig"
    )


def checkpoint_label_map(path):
    ckpt = load_checkpoint(path)

    if ckpt.empty:
        return {}

    return (
        ckpt
        .drop_duplicates(
            subset=["annotation_id"],
            keep="last"
        )
        .set_index("annotation_id")["label"]
        .to_dict()
    )

## 14. Genel LLM etiketleme motoru

In [65]:
import math


def run_labeling(
    queue_df,
    provider,
    label_func,
    interval_seconds,
):
    queue_df = queue_df.copy()

    checkpoint_file = checkpoint_path(
        provider,
        queue_df["dataset"].iloc[0]
        if len(queue_df)
        else "empty"
    )

    existing = checkpoint_label_map(
        checkpoint_file
    )

    # map() boş döndüğünde pandas kolonu float64 yapabilir;
    # daha sonra 'positive/neutral/negative' atamasında hata vermemesi
    # için etiketi baştan nullable string dtype olarak tut.
    queue_df[f"{provider}_label"] = (
        queue_df["annotation_id"]
        .map(existing)
        .astype("string")
    )

    valid_existing = (
        queue_df[f"{provider}_label"]
        .isin(VALID_LABELS)
    )

    remaining = queue_df.index[
        ~valid_existing
    ].tolist()

    total_batches = math.ceil(
        len(remaining) / BATCH_SIZE
    )

    print("\n" + "#" * 110)
    print(f"{provider.upper()} | {queue_df['dataset'].iloc[0]}")
    print(f"Toplam unique kayıt : {len(queue_df):,}")
    print(f"Checkpoint'ten hazır: {valid_existing.sum():,}")
    print(f"İşlenecek           : {len(remaining):,}")
    print(f"Batch                : {total_batches:,}")
    print(f"Checkpoint           : {checkpoint_file}")
    print("#" * 110)

    last_call = 0.0

    for batch_no, start in enumerate(
        range(0, len(remaining), BATCH_SIZE),
        start=1
    ):

        batch_indices = remaining[
            start:start + BATCH_SIZE
        ]

        texts = [
            str(queue_df.loc[idx, "text"])
            for idx in batch_indices
        ]

        elapsed = time.time() - last_call

        if elapsed < interval_seconds:
            time.sleep(
                interval_seconds - elapsed
            )

        print(
            f"[{batch_no}/{total_batches}] "
            f"{provider} | "
            f"{len(batch_indices)} kayıt"
        )

        labels = label_func(texts)

        # Model cevabı beklenen sayıda değilse zip() eksik kayıtları
        # sessizce atlamasın; batch checkpoint'e hiç yazılmasın.
        if len(labels) != len(batch_indices):
            raise RuntimeError(
                f"{provider} batch {batch_no}: beklenen "
                f"{len(batch_indices)} label, gelen {len(labels)}"
            )

        last_call = time.time()

        checkpoint_rows = []

        for idx, label in zip(
            batch_indices,
            labels
        ):
            annotation_id = str(
                queue_df.loc[idx, "annotation_id"]
            )

            text_key = str(
                queue_df.loc[idx, "text_key"]
            )

            text = str(
                queue_df.loc[idx, "text"]
            )

            queue_df.loc[
                idx,
                f"{provider}_label"
            ] = label

            checkpoint_rows.append({
                "annotation_id": annotation_id,
                "text_key": text_key,
                "text": text,
                "label": label,
            })

        append_checkpoint(
            checkpoint_file,
            checkpoint_rows
        )

        print(
            f"  ✅ checkpoint yazıldı: "
            f"{len(checkpoint_rows)}"
        )

    return queue_df

## 15. Twitter için ChatGPT + Gemini

Önce ChatGPT, ardından Gemini çalışır.

In [66]:
# Twitter queue

twitter_chatgpt = run_labeling(
    queue_df=twitter_queue_unique,
    provider="chatgpt",
    label_func=ask_chatgpt_batch,
    interval_seconds=OPENAI_REQUEST_INTERVAL,
)

twitter_gemini = run_labeling(
    queue_df=twitter_chatgpt.rename(
        columns={"chatgpt_label": "chatgpt_label"}
    ),
    provider="gemini",
    label_func=ask_gemini_batch,
    interval_seconds=GEMINI_REQUEST_INTERVAL,
)

print("\n✅ Twitter LLM annotation tamamlandı.")

##############################################################################################################
CHATGPT | TwitterFinancialNewsSentiment
Toplam unique kayıt : 11,924
Checkpoint'ten hazır: 0
İşlenecek           : 11,924
Batch                : 2,385
Checkpoint           : D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\annotations\reannotation_21\checkpoints\twitterfinancialnewssentiment_chatgpt_checkpoint.csv
##############################################################################################################
[1/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[2/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[3/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[4/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[5/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[6/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[7/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[8/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[9/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[10/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[11/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[12/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[13/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[14/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[15/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[16/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[17/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[18/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[19/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[20/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[21/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[22/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[23/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[24/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[25/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[26/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[27/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[28/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[29/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[30/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[31/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[32/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[33/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[34/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[35/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[36/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[37/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[38/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[39/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[40/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[41/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[42/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[43/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[44/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[45/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[46/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[47/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[48/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[49/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[50/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[51/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[52/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[53/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[54/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[55/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[56/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[57/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[58/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[59/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[60/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[61/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[62/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[63/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[64/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[65/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[66/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[67/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[68/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[69/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[70/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[71/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[72/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[73/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[74/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[75/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[76/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[77/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[78/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[79/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[80/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[81/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[82/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[83/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[84/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[85/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[86/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[87/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[88/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[89/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[90/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[91/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[92/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[93/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[94/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[95/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[96/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[97/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[98/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[99/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[100/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[101/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[102/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[103/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[104/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[105/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[106/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[107/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[108/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[109/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[110/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[111/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[112/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[113/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[114/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[115/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[116/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[117/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[118/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[119/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[120/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[121/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[122/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[123/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[124/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[125/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[126/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[127/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[128/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[129/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[130/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[131/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[132/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[133/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[134/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[135/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[136/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[137/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[138/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[139/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[140/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[141/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[142/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[143/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[144/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[145/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[146/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[147/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[148/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[149/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[150/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[151/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[152/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[153/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[154/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[155/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[156/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[157/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[158/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[159/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[160/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[161/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[162/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[163/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[164/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[165/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[166/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[167/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[168/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[169/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[170/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[171/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[172/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[173/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[174/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[175/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[176/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[177/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[178/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[179/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[180/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[181/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[182/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[183/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[184/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[185/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[186/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[187/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[188/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[189/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[190/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[191/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[192/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[193/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[194/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[195/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[196/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[197/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[198/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[199/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[200/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[201/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[202/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[203/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[204/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[205/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[206/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[207/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[208/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[209/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[210/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[211/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[212/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[213/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[214/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[215/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[216/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[217/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[218/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[219/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[220/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[221/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[222/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[223/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[224/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[225/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[226/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[227/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[228/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[229/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[230/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[231/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[232/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[233/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[234/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[235/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[236/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[237/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[238/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[239/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[240/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[241/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[242/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[243/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[244/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[245/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[246/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[247/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[248/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[249/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[250/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[251/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[252/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[253/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[254/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[255/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[256/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[257/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[258/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[259/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[260/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[261/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[262/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[263/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[264/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[265/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[266/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[267/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[268/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[269/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[270/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[271/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[272/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[273/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[274/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[275/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[276/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[277/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[278/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[279/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[280/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[281/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[282/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[283/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[284/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[285/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[286/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[287/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[288/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[289/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[290/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[291/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[292/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[293/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[294/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[295/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[296/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[297/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[298/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[299/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[300/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[301/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[302/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[303/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[304/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[305/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[306/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[307/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[308/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[309/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[310/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[311/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[312/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[313/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[314/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[315/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[316/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[317/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[318/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[319/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[320/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[321/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[322/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[323/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[324/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[325/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[326/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[327/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[328/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[329/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[330/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[331/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[332/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[333/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[334/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[335/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[336/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[337/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[338/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[339/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[340/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[341/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[342/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[343/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[344/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[345/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[346/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[347/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[348/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[349/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[350/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[351/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[352/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[353/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[354/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[355/2385] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5

## 16. PhraseBank için ChatGPT + Gemini

Dört agreement konfigürasyonunun benzersiz cümleleri tek API kuyruğunda etiketlenir.

In [67]:
phrasebank_chatgpt = run_labeling(
    queue_df=phrasebank_queue,
    provider="chatgpt",
    label_func=ask_chatgpt_batch,
    interval_seconds=OPENAI_REQUEST_INTERVAL,
)

phrasebank_gemini = run_labeling(
    queue_df=phrasebank_chatgpt,
    provider="gemini",
    label_func=ask_gemini_batch,
    interval_seconds=GEMINI_REQUEST_INTERVAL,
)

print("\n✅ PhraseBank LLM annotation tamamlandı.")

##############################################################################################################
CHATGPT | FinancialPhraseBank
Toplam unique kayıt : 4,838
Checkpoint'ten hazır: 0
İşlenecek           : 4,838
Batch                : 968
Checkpoint           : D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\annotations\reannotation_21\checkpoints\financialphrasebank_chatgpt_checkpoint.csv
##############################################################################################################
[1/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[2/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[3/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[4/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[5/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[6/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[7/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[8/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[9/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[10/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[11/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[12/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[13/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[14/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[15/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[16/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[17/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[18/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[19/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[20/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[21/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[22/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[23/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[24/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[25/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[26/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[27/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[28/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[29/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[30/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[31/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[32/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[33/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[34/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[35/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[36/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[37/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[38/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[39/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[40/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[41/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[42/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[43/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[44/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[45/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[46/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[47/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[48/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[49/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[50/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[51/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[52/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[53/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[54/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[55/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[56/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[57/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[58/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[59/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[60/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[61/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[62/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[63/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[64/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[65/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[66/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[67/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[68/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[69/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[70/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[71/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[72/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[73/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[74/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[75/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[76/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[77/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[78/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[79/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[80/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[81/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[82/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[83/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[84/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[85/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[86/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[87/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[88/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[89/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[90/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[91/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[92/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[93/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[94/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[95/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[96/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[97/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[98/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[99/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[100/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[101/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[102/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[103/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[104/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[105/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[106/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[107/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[108/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[109/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[110/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[111/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[112/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[113/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[114/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[115/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[116/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[117/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[118/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[119/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[120/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[121/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[122/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[123/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[124/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[125/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[126/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[127/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[128/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[129/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[130/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[131/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[132/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[133/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[134/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[135/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[136/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[137/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[138/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[139/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[140/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[141/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[142/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[143/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[144/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[145/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[146/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[147/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[148/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[149/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[150/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[151/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[152/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[153/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[154/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[155/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[156/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[157/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[158/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[159/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[160/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[161/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[162/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[163/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[164/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[165/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[166/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[167/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[168/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[169/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[170/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[171/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[172/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[173/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[174/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[175/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[176/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[177/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[178/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[179/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[180/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[181/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[182/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[183/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[184/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[185/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[186/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[187/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[188/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[189/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[190/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[191/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[192/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[193/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[194/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[195/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[196/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[197/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[198/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[199/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[200/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[201/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[202/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[203/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[204/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[205/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[206/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[207/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[208/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[209/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[210/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[211/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[212/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[213/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[214/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[215/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[216/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[217/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[218/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[219/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[220/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[221/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[222/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[223/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[224/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[225/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[226/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[227/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[228/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[229/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[230/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[231/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[232/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[233/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[234/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[235/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[236/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[237/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[238/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[239/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[240/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[241/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[242/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[243/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[244/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[245/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[246/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[247/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[248/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[249/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[250/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[251/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[252/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[253/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[254/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[255/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[256/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[257/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[258/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[259/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[260/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[261/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[262/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[263/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[264/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[265/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[266/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[267/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[268/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[269/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[270/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[271/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[272/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[273/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[274/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[275/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[276/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[277/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[278/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[279/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[280/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[281/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[282/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[283/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[284/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[285/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[286/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[287/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[288/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[289/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[290/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[291/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[292/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[293/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[294/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[295/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[296/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[297/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[298/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[299/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[300/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[301/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[302/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[303/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[304/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[305/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[306/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[307/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[308/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[309/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[310/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[311/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[312/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[313/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[314/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[315/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[316/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[317/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[318/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[319/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[320/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[321/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[322/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[323/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[324/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[325/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[326/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[327/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[328/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[329/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[330/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[331/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[332/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[333/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[334/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[335/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[336/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[337/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[338/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[339/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[340/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[341/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[342/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[343/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[344/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[345/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[346/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[347/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[348/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[349/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[350/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[351/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[352/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[353/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[354/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[355/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[356/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[357/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[358/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[359/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[360/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[361/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[362/968] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5

## 17. LLM sonuçlarını tüm PhraseBank konfigürasyonlarına dağıt

Aynı cümlenin 50/66/75/AllAgree sürümlerinde bulunması halinde aynı ChatGPT/Gemini çıktısı kullanılır.

In [68]:
# Twitter final
twitter_unique_final = twitter_gemini.copy()

twitter_final = twitter_df.merge(
    twitter_unique_final[
        [
            "text_key",
            "chatgpt_label",
            "gemini_label",
        ]
    ],
    left_on="text",
    right_on=twitter_unique_final["text"].map(normalize_text)
        if False else "text_key",
    how="left",
    suffixes=("", "_llm")
)

# Yukarıdaki merge için güvenli yol:
twitter_unique_map = (
    twitter_unique_final
    .set_index("text_key")[
        ["chatgpt_label", "gemini_label"]
    ]
)

twitter_df["text_key"] = twitter_df["text"].map(normalize_text)
twitter_df["chatgpt_label"] = twitter_df["text_key"].map(
    twitter_unique_map["chatgpt_label"]
)
twitter_df["gemini_label"] = twitter_df["text_key"].map(
    twitter_unique_map["gemini_label"]
)

twitter_final = twitter_df.copy()

# PhraseBank tüm config'ler
phrasebank_label_map = (
    phrasebank_gemini
    .set_index("text_key")[
        ["chatgpt_label", "gemini_label"]
    ]
)

phrasebank_final_all = phrasebank_all.copy()

phrasebank_final_all["chatgpt_label"] = (
    phrasebank_final_all["text_key"]
    .map(phrasebank_label_map["chatgpt_label"])
)

phrasebank_final_all["gemini_label"] = (
    phrasebank_final_all["text_key"]
    .map(phrasebank_label_map["gemini_label"])
)

print("Twitter final:", twitter_final.shape)
print("PhraseBank final:", phrasebank_final_all.shape)

Twitter final: (11931, 10)
PhraseBank final: (14780, 9)

## 18. Final dosyaları kaydet

In [69]:
twitter_final_path = FINAL_DIR / "twitter_financial_news_reannotated.csv"
phrasebank_final_path = FINAL_DIR / "financial_phrasebank_reannotated_all_configs.csv"

twitter_final.to_csv(
    twitter_final_path,
    index=False,
    encoding="utf-8-sig"
)

phrasebank_final_all.to_csv(
    phrasebank_final_path,
    index=False,
    encoding="utf-8-sig"
)

# Birleşik long-form dosya
twitter_export = twitter_final[
    [
        "dataset",
        "config",
        "source_original_split",
        "source_index",
        "text",
        "human_label",
        "chatgpt_label",
        "gemini_label",
    ]
].copy()

phrasebank_export = phrasebank_final_all[
    [
        "dataset",
        "config",
        "source_index",
        "text",
        "human_label",
        "chatgpt_label",
        "gemini_label",
    ]
].copy()

combined_final = pd.concat(
    [twitter_export, phrasebank_export],
    ignore_index=True
)

combined_path = FINAL_DIR / "21_reannotation_combined.csv"

combined_final.to_csv(
    combined_path,
    index=False,
    encoding="utf-8-sig"
)

print("✅ Twitter  :", twitter_final_path)
print("✅ PhraseBank:", phrasebank_final_path)
print("✅ Combined  :", combined_path)

✅ Twitter  : D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\annotations\reannotation_21\final\twitter_financial_news_reannotated.csv
✅ PhraseBank: D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\annotations\reannotation_21\final\financial_phrasebank_reannotated_all_configs.csv
✅ Combined  : D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\annotations\reannotation_21\final\21_reannotation_combined.csv

## 19. Üçlü etiket kalite kontrolü

In [70]:
def valid_label_mask(df, *cols):
    mask = pd.Series(
        True,
        index=df.index
    )

    for col in cols:
        mask &= df[col].isin(VALID_LABELS)

    return mask


print("=" * 100)
print("TWITTER LABEL DURUMU")
print("=" * 100)
print(
    twitter_final[
        ["human_label", "chatgpt_label", "gemini_label"]
    ].notna().mean()
)

for config in PHRASEBANK_CONFIGS:
    cfg = phrasebank_final_all[
        phrasebank_final_all["config"] == config
    ]

    print("\n" + "-" * 80)
    print("PHRASEBANK", config)
    print(
        cfg[
            ["human_label", "chatgpt_label", "gemini_label"]
        ].notna().mean()
    )

====================================================================================================
TWITTER LABEL DURUMU
====================================================================================================
human_label      1.0
chatgpt_label    1.0
gemini_label     1.0
dtype: float64

--------------------------------------------------------------------------------
PHRASEBANK 50agree
human_label      1.0
chatgpt_label    1.0
gemini_label     1.0
dtype: float64

--------------------------------------------------------------------------------
PHRASEBANK 66agree
human_label      1.0
chatgpt_label    1.0
gemini_label     1.0
dtype: float64

--------------------------------------------------------------------------------
PHRASEBANK 75agree
human_label      1.0
chatgpt_label    1.0
gemini_label     1.0
dtype: float64

--------------------------------------------------------------------------------
PHRASEBANK allagree
human_label      1.0
chatgpt_label    1.0
gemini_label     1.0
dtype: float64

## 20. Pairwise Cohen's Kappa + confusion matrix

Burada:
- Human ↔ ChatGPT
- Human ↔ Gemini
- ChatGPT ↔ Gemini

hesaplanır.

`agreement` yalnızca aynı etiket yüzdesidir.
`Cohen's κ` ise şansa göre düzeltilmiş anlaşmadır.

In [71]:
PAIR_DEFS = [
    ("human_label", "chatgpt_label", "Human vs ChatGPT"),
    ("human_label", "gemini_label", "Human vs Gemini"),
    ("chatgpt_label", "gemini_label", "ChatGPT vs Gemini"),
]


def pairwise_kappa(df, col_a, col_b):
    data = df[
        df[col_a].isin(VALID_LABELS)
        & df[col_b].isin(VALID_LABELS)
    ].copy()

    if data.empty:
        return {
            "n": 0,
            "agreement": np.nan,
            "kappa": np.nan,
        }

    agreement = (
        data[col_a] == data[col_b]
    ).mean()

    kappa = cohen_kappa_score(
        data[col_a],
        data[col_b],
        labels=VALID_LABELS
    )

    return {
        "n": len(data),
        "agreement": agreement,
        "kappa": kappa,
    }


def confusion_for_pair(df, col_a, col_b):
    data = df[
        df[col_a].isin(VALID_LABELS)
        & df[col_b].isin(VALID_LABELS)
    ].copy()

    return pd.crosstab(
        data[col_a],
        data[col_b],
        rownames=[col_a],
        colnames=[col_b]
    ).reindex(
        index=VALID_LABELS,
        columns=VALID_LABELS,
        fill_value=0
    )


kappa_rows = []


def analyze_dataset(df, dataset_name):
    print("\n" + "=" * 110)
    print(dataset_name)
    print("=" * 110)

    for col_a, col_b, label_name in PAIR_DEFS:

        result = pairwise_kappa(
            df,
            col_a,
            col_b
        )

        kappa_rows.append({
            "dataset": dataset_name,
            "comparison": label_name,
            "n": result["n"],
            "agreement": result["agreement"],
            "kappa": result["kappa"],
        })

        print(
            f"\n{label_name}"
        )
        print(
            f"N         : {result['n']:,}"
        )
        print(
            f"Agreement : {result['agreement']:.4f}"
            if pd.notna(result["agreement"])
            else "Agreement : NaN"
        )
        print(
            f"Cohen κ  : {result['kappa']:.4f}"
            if pd.notna(result["kappa"])
            else "Cohen κ  : NaN"
        )

        print(
            "\nConfusion matrix:"
        )

        display(
            confusion_for_pair(
                df,
                col_a,
                col_b
            )
        )


analyze_dataset(
    twitter_final,
    "Twitter Financial News Sentiment"
)

for config in PHRASEBANK_CONFIGS:
    cfg_df = phrasebank_final_all[
        phrasebank_final_all["config"] == config
    ].copy()

    analyze_dataset(
        cfg_df,
        f"Financial PhraseBank - {config}"
    )

==============================================================================================================
Twitter Financial News Sentiment
==============================================================================================================

Human vs ChatGPT
N         : 11,931
Agreement : 0.7191
Cohen κ  : 0.5528

Confusion matrix:

chatgpt_label  negative  neutral  positive
human_label
negative           1693       75        21
neutral            1291     4684      1769
positive             57      138      2203

Human vs Gemini
N         : 11,931
Agreement : 0.7691
Cohen κ  : 0.6086

Confusion matrix:

gemini_label  negative  neutral  positive
human_label
negative          1588      183        18
neutral            875     5450      1419
positive            41      219      2138

ChatGPT vs Gemini
N         : 11,931
Agreement : 0.8734
Cohen κ  : 0.8036

Confusion matrix:

gemini_label   negative  neutral  positive
chatgpt_label
negative           2388      636        17
neutral             109     4631       157
positive              7      585      3401

==============================================================================================================
Financial PhraseBank - 50agree
==============================================================================================================

Human vs ChatGPT
N         : 4,846
Agreement : 0.8401
Cohen κ  : 0.7258

Confusion matrix:

chatgpt_label  negative  neutral  positive
human_label
negative            579       24         1
neutral             142     2289       448
positive              8      152      1203

Human vs Gemini
N         : 4,846
Agreement : 0.8632
Cohen κ  : 0.7527

Confusion matrix:

gemini_label  negative  neutral  positive
human_label
negative           539       63         2
neutral             76     2546       257
positive             2      263      1098

ChatGPT vs Gemini
N         : 4,846
Agreement : 0.8783
Cohen κ  : 0.7915

Confusion matrix:

gemini_label   negative  neutral  positive
chatgpt_label
negative            602      124         3
neutral              15     2375        75
positive              0      373      1279

==============================================================================================================
Financial PhraseBank - 66agree
==============================================================================================================

Human vs ChatGPT
N         : 4,217
Agreement : 0.8840
Cohen κ  : 0.7983

Confusion matrix:

chatgpt_label  negative  neutral  positive
human_label
negative            505        9         0
neutral             108     2136       291
positive              5       76      1087

Human vs Gemini
N         : 4,217
Agreement : 0.9051
Cohen κ  : 0.8279

Confusion matrix:

gemini_label  negative  neutral  positive
human_label
negative           483       30         1
neutral             58     2316       161
positive             0      150      1018

ChatGPT vs Gemini
N         : 4,217
Agreement : 0.9018
Cohen κ  : 0.8302

Confusion matrix:

gemini_label   negative  neutral  positive
chatgpt_label
negative            532       85         1
neutral               9     2152        60
positive              0      259      1119

==============================================================================================================
Financial PhraseBank - 75agree
==============================================================================================================

Human vs ChatGPT
N         : 3,453
Agreement : 0.9230
Cohen κ  : 0.8617

Confusion matrix:

chatgpt_label  negative  neutral  positive
human_label
negative            415        5         0
neutral              64     1913       169
positive              3       25       859

Human vs Gemini
N         : 3,453
Agreement : 0.9406
Cohen κ  : 0.8898

Confusion matrix:

gemini_label  negative  neutral  positive
human_label
negative           403       17         0
neutral             32     2019        95
positive             0       61       826

ChatGPT vs Gemini
N         : 3,453
Agreement : 0.9305
Cohen κ  : 0.8762

Confusion matrix:

gemini_label   negative  neutral  positive
chatgpt_label
negative            430       52         0
neutral               5     1900        38
positive              0      145       883

==============================================================================================================
Financial PhraseBank - allagree
==============================================================================================================

Human vs ChatGPT
N         : 2,264
Agreement : 0.9655
Cohen κ  : 0.9376

Confusion matrix:

chatgpt_label  negative  neutral  positive
human_label
negative            302        1         0
neutral              22     1321        48
positive              1        6       563

Human vs Gemini
N         : 2,264
Agreement : 0.9686
Cohen κ  : 0.9426

Confusion matrix:

gemini_label  negative  neutral  positive
human_label
negative           300        3         0
neutral             13     1342        36
positive             0       19       551

ChatGPT vs Gemini
N         : 2,264
Agreement : 0.9647
Cohen κ  : 0.9365

Confusion matrix:

gemini_label   negative  neutral  positive
chatgpt_label
negative            311       14         0
neutral               2     1306        20
positive              0       44       567

## 21. Kappa sonuçlarını tablo olarak kaydet

In [72]:
kappa_results_df = pd.DataFrame(kappa_rows)

kappa_results_path = (
    RESULT_DIR / "cohen_kappa_results.csv"
)

kappa_results_df.to_csv(
    kappa_results_path,
    index=False,
    encoding="utf-8-sig"
)

display(
    kappa_results_df.sort_values(
        ["dataset", "comparison"]
    )
)

print(
    "\n✅ Kappa sonuçları:",
    kappa_results_path
)

                             dataset         comparison      n  agreement     kappa
5     Financial PhraseBank - 50agree  ChatGPT vs Gemini   4846   0.878250  0.791497
3     Financial PhraseBank - 50agree   Human vs ChatGPT   4846   0.840074  0.725765
4     Financial PhraseBank - 50agree    Human vs Gemini   4846   0.863186  0.752720
8     Financial PhraseBank - 66agree  ChatGPT vs Gemini   4217   0.901826  0.830156
6     Financial PhraseBank - 66agree   Human vs ChatGPT   4217   0.884041  0.798340
7     Financial PhraseBank - 66agree    Human vs Gemini   4217   0.905146  0.827867
11    Financial PhraseBank - 75agree  ChatGPT vs Gemini   3453   0.930495  0.876168
9     Financial PhraseBank - 75agree   Human vs ChatGPT   3453   0.922966  0.861656
10    Financial PhraseBank - 75agree    Human vs Gemini   3453   0.940631  0.889799
14   Financial PhraseBank - allagree  ChatGPT vs Gemini   2264   0.964664  0.936536
12   Financial PhraseBank - allagree   Human vs ChatGPT   2264   0.965548  0.937638
13   Financial PhraseBank - allagree    Human vs Gemini   2264   0.968640  0.942570
2   Twitter Financial News Sentiment  ChatGPT vs Gemini  11931   0.873355  0.803623
0   Twitter Financial News Sentiment   Human vs ChatGPT  11931   0.719135  0.552842
1   Twitter Financial News Sentiment    Human vs Gemini  11931   0.769089  0.608591

✅ Kappa sonuçları: D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\annotations\reannotation_21\results\cohen_kappa_results.csv

## 22. İsterseniz 3 annotator için Fleiss' Kappa

Cohen's Kappa ikili karşılaştırmadır. Üç etiketi tek bir çok-rater ölçüsünde özetlemek için Fleiss' Kappa da hesaplanabilir.

In [73]:
from statsmodels.stats.inter_rater import fleiss_kappa

def calculate_fleiss_kappa(df, dataset_name):
    data = df[
        df["human_label"].isin(VALID_LABELS)
        & df["chatgpt_label"].isin(VALID_LABELS)
        & df["gemini_label"].isin(VALID_LABELS)
    ].copy()

    if data.empty:
        return None

    label_to_col = {
        label: i
        for i, label in enumerate(VALID_LABELS)
    }

    counts = np.zeros(
        (len(data), len(VALID_LABELS)),
        dtype=int
    )

    for row_idx, (_, row) in enumerate(data.iterrows()):

        for col in [
            "human_label",
            "chatgpt_label",
            "gemini_label",
        ]:
            counts[
                row_idx,
                label_to_col[row[col]]
            ] += 1

    result = fleiss_kappa(
        counts,
        method="fleiss"
    )

    print(
        f"{dataset_name}: "
        f"Fleiss κ = {result:.4f} "
        f"(N={len(data):,})"
    )

    return result


fleiss_results = []

twitter_fleiss = calculate_fleiss_kappa(
    twitter_final,
    "Twitter Financial News Sentiment"
)

fleiss_results.append({
    "dataset": "Twitter Financial News Sentiment",
    "fleiss_kappa": twitter_fleiss
})

for config in PHRASEBANK_CONFIGS:

    cfg = phrasebank_final_all[
        phrasebank_final_all["config"] == config
    ].copy()

    value = calculate_fleiss_kappa(
        cfg,
        f"Financial PhraseBank - {config}"
    )

    fleiss_results.append({
        "dataset": f"Financial PhraseBank - {config}",
        "fleiss_kappa": value
    })

fleiss_df = pd.DataFrame(fleiss_results)

fleiss_path = RESULT_DIR / "fleiss_kappa_results.csv"

fleiss_df.to_csv(
    fleiss_path,
    index=False,
    encoding="utf-8-sig"
)

display(fleiss_df)

print(
    "✅ Fleiss sonuçları:",
    fleiss_path
)

Twitter Financial News Sentiment: Fleiss κ = 0.6532 (N=11,931)
Financial PhraseBank - 50agree: Fleiss κ = 0.7562 (N=4,846)
Financial PhraseBank - 66agree: Fleiss κ = 0.8184 (N=4,217)
Financial PhraseBank - 75agree: Fleiss κ = 0.8756 (N=3,453)
Financial PhraseBank - allagree: Fleiss κ = 0.9389 (N=2,264)

                            dataset  fleiss_kappa
0  Twitter Financial News Sentiment      0.653153
1    Financial PhraseBank - 50agree      0.756205
2    Financial PhraseBank - 66agree      0.818404
3    Financial PhraseBank - 75agree      0.875612
4   Financial PhraseBank - allagree      0.938883

✅ Fleiss sonuçları: D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\annotations\reannotation_21\results\fleiss_kappa_results.csv

## 23. Final özet

Bu notebook sonunda:
- raw Twitter + PhraseBank verileri yeniden etiketlenmiş olur,
- her kayıtta human/reference + ChatGPT + Gemini etiketleri bulunur,
- pairwise Cohen's κ hesaplanır,
- istenirse üç-rater Fleiss' κ hesaplanır,
- checkpoint'ler sayesinde kesilirse devam edilebilir.

Önemli: `consensus` dosyası oluşturulmuyor. Kappa hesaplamasında yalnızca iki/üç annotator'ın gerçekten geçerli etiketi olan kayıtlar kullanılıyor; ChatGPT==Gemini filtresi uygulanarak veri küçültülmüyor.