# 22 - FiQA yeniden etiketleme: ChatGPT + Gemini

Bu notebook **FiQA Sentiment Classification** veri setinin tamamını yeniden etiketler.

Her kayıt için:
- `human_label` = FiQA'nın orijinal `score` değerinden türetilen referans etiket
- `chatgpt_label` = OpenAI
- `gemini_label` = Gemini

FiQA'nın train/test/valid splitleri burada tek bir veri kümesi olarak birleştirilir.

## Güvenlik ve devam edebilme

- API anahtarları notebook içine yazılmaz; environment variable kullanılır.
- ChatGPT ve Gemini için ayrı checkpoint CSV dosyaları tutulur.
- Her başarılı batch hemen diske yazılır.
- Notebook kesilirse daha önce tamamlanan kayıtlar tekrar API'ye gönderilmez.
- Sonuçta tek bir final CSV oluşturulur.

In [1]:
%pip install -q -U datasets openai google-genai pandas scikit-learn statsmodels

Note: you may need to restart the kernel to use updated packages.

[notice] A new release of pip is available: 25.3 -> 26.2.1
[notice] To update, run: python.exe -m pip install --upgrade pip

In [2]:
from pathlib import Path
import os
import json
import re
import time
import math
from getpass import getpass

import pandas as pd
import numpy as np

from IPython.display import display
from datasets import load_dataset
from sklearn.metrics import cohen_kappa_score

pd.set_option("display.max_colwidth", 180)
pd.set_option("display.max_columns", 100)
pd.set_option("display.width", 220)

VALID_LABELS = ["negative", "neutral", "positive"]

# ------------------------------------------------------------
# API / batch ayarları
# ------------------------------------------------------------

BATCH_SIZE = 5
MAX_RETRIES = 8

GEMINI_REQUEST_INTERVAL = 5.0
OPENAI_REQUEST_INTERVAL = 0.5

OPENAI_MODEL = "gpt-5.6-luna"
GEMINI_MODEL = "gemini-3.5-flash-lite"

# ------------------------------------------------------------
# Çıktı klasörleri
# ------------------------------------------------------------

PROJECT_DIR = Path(
    r"D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis"
)

DATA_DIR = PROJECT_DIR / "db"

OUTPUT_DIR = DATA_DIR / "annotations" / "reannotation_22_fiqa"
CHECKPOINT_DIR = OUTPUT_DIR / "checkpoints"
FINAL_DIR = OUTPUT_DIR / "final"
RESULT_DIR = OUTPUT_DIR / "results"

for p in [OUTPUT_DIR, CHECKPOINT_DIR, FINAL_DIR, RESULT_DIR]:
    p.mkdir(parents=True, exist_ok=True)

print("OUTPUT_DIR :", OUTPUT_DIR)
print("BATCH_SIZE :", BATCH_SIZE)
print("OpenAI     :", OPENAI_MODEL)
print("Gemini     :", GEMINI_MODEL)

OUTPUT_DIR : D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\annotations\reannotation_22_fiqa
BATCH_SIZE : 5
OpenAI     : gpt-5.6-luna
Gemini     : gemini-3.5-flash-lite

## 2. API anahtarları

Environment variable:
- `OPENAI_API_KEY`
- `GEMINI_API_KEY`

Bulunamazsa notebook güvenli şekilde `getpass()` ile sorar.

In [3]:
OPENAI_API_KEY =  "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";

if not OPENAI_API_KEY:
    OPENAI_API_KEY = getpass("OPENAI_API_KEY girin: ").strip()

if not OPENAI_API_KEY:
    raise RuntimeError("OPENAI_API_KEY bulunamadı.")


GEMINI_API_KEY ="AQ.Ab8RN6IVVX_2kWKkap7nUDkXllD4tl9j5KY4E5s7FF86rZ3huA";
if not GEMINI_API_KEY:
    GEMINI_API_KEY = getpass("GEMINI_API_KEY girin: ").strip()

if not GEMINI_API_KEY:
    raise RuntimeError("GEMINI_API_KEY bulunamadı.")

print("OpenAI key: bulundu")
print("Gemini key : bulundu")

OpenAI key: bulundu
Gemini key : bulundu

In [4]:
from openai import OpenAI
from google import genai
from google.genai import types

openai_client = OpenAI(api_key=OPENAI_API_KEY)

gemini_client = genai.Client(
    api_key=GEMINI_API_KEY,
    http_options=types.HttpOptions(timeout=60000),
)

print("✅ OpenAI client hazır")
print("✅ Gemini client hazır")

✅ OpenAI client hazır
✅ Gemini client hazır

## 3. FiQA'yı indir

Train + test + valid birlikte tek veri kümesi olarak kullanılır.

In [5]:
dataset = load_dataset(
    "TheFinAI/fiqa-sentiment-classification"
)

print(dataset)

Warning: You are sending unauthenticated requests to the HF Hub. Please set a HF_TOKEN to enable higher rate limits and faster downloads.

DatasetDict({
    train: Dataset({
        features: ['_id', 'sentence', 'target', 'aspect', 'score', 'type'],
        num_rows: 822
    })
    test: Dataset({
        features: ['_id', 'sentence', 'target', 'aspect', 'score', 'type'],
        num_rows: 234
    })
    valid: Dataset({
        features: ['_id', 'sentence', 'target', 'aspect', 'score', 'type'],
        num_rows: 117
    })
})

In [6]:
# Tüm splitleri birleştir
df_fiqa = pd.concat(
    [
        dataset["train"].to_pandas(),
        dataset["test"].to_pandas(),
        dataset["valid"].to_pandas(),
    ],
    ignore_index=True,
)

# Sadece gerekli alanları tut
df_fiqa = df_fiqa[
    ["sentence", "score"]
].rename(
    columns={
        "sentence": "text",
    }
)

# FiQA score -> 3 sınıflı referans label
df_fiqa["human_label"] = df_fiqa["score"].apply(
    lambda x:
        "positive" if x > 0
        else "negative" if x < 0
        else "neutral"
)

df_fiqa["text"] = (
    df_fiqa["text"]
    .astype(str)
    .str.strip()
)

df_fiqa = df_fiqa[
    df_fiqa["text"].ne("")
].copy()

df_fiqa["dataset"] = "FiQA"
df_fiqa["config"] = "full"
df_fiqa["source_index"] = np.arange(len(df_fiqa))

print("=" * 100)
print("FiQA")
print("=" * 100)
print("Toplam:", len(df_fiqa))
print("\nHuman label:")
print(df_fiqa["human_label"].value_counts())

display(
    df_fiqa[
        ["text", "score", "human_label"]
    ].head(20)
)

====================================================================================================
FiQA
====================================================================================================
Toplam: 1173

Human label:
human_label
positive    760
negative    399
neutral      14
Name: count, dtype: int64

                                                                             text  score human_label
0                              Royal Mail chairman Donald Brydon set to step down -0.374    negative
1                                  Slump in Weir leads FTSE down from record high -0.827    negative
2                      AstraZeneca wins FDA approval for key new lung cancer pill  0.549    positive
3            UPDATE 1-Lloyds to cut 945 jobs as part of 3-year restructuring plan -0.266    negative
4                Standard Chartered Shifts Emerging-Markets Strategy After Losses -0.461    negative
5                       AstraZeneca's Lung Cancer Drug Tagrisso Gets FDA Approval  0.393    positive
6   Severn Trent share price rises as first half profit inches up as customer ...  0.526    positive
7              Glencore sees Tripoli-based NOC as sole legal seller of Libyan oil  0.037    positive
8             Lloyds to cut 945 jobs as part of three-year restructuring strategy -0.532    negative
9                                   AstraZeneca to Buy ZS Pharma for $2.7 Billion  0.593    positive
10                            Ackman, in email, says supports Valeant CEO Pearson  0.166    positive
11                       AstraZeneca sells US drug rights to Perrigo for $380 mln  0.326    positive
12            UPDATE 1-AstraZeneca buys ZS Pharma for $2.7 billion, pips Actelion  0.468    positive
13                                 CORRECTED-Shire to buy Dyax for about $5.9 bln  0.402    positive
14                  Barclays poised to replace Sir Mike Rake as he heads for exit  0.077    positive
15                            AstraZeneca Acquires ZS Pharma in $2.7 Billion Deal  0.520    positive
16                AstraZeneca shares climb 3% as drug maker ups profits forecasts  0.640    positive
17  Peroni and Grolsch put up for sale as AB InBev plans acquisition of SABMiller  0.551    positive
18                   easyJet expects resilient demand to withstand security fears  0.165    positive
19                                     Compass Group says positive for year ahead  0.634    positive

## 4. Annotation queue

Aynı normalize edilmiş text birden fazla kez bulunuyorsa API'ye yalnızca bir kez gönderilir.

In [7]:
def normalize_text(text):
    text = str(text)
    text = re.sub(r"\s+", " ", text).strip().lower()
    return text


df_fiqa["text_key"] = df_fiqa["text"].map(normalize_text)

duplicate_count = df_fiqa["text_key"].duplicated().sum()

print("Toplam kayıt          :", len(df_fiqa))
print("Tekrarlı text sayısı  :", duplicate_count)
print("Unique text sayısı    :", df_fiqa["text_key"].nunique())

fiqa_queue = (
    df_fiqa
    .sort_values("source_index")
    .drop_duplicates(
        subset=["text_key"],
        keep="first"
    )
    [
        [
            "dataset",
            "config",
            "source_index",
            "text",
            "human_label",
            "score",
            "text_key",
        ]
    ]
    .copy()
)

fiqa_queue["annotation_id"] = [
    f"fiqa_{i:06d}"
    for i in range(len(fiqa_queue))
]

fiqa_queue["chatgpt_label"] = pd.Series(
    pd.NA,
    index=fiqa_queue.index,
    dtype="string"
)

fiqa_queue["gemini_label"] = pd.Series(
    pd.NA,
    index=fiqa_queue.index,
    dtype="string"
)

print("\nAPI queue:", len(fiqa_queue))
display(
    fiqa_queue[
        ["annotation_id", "text", "human_label"]
    ].head(20)
)

Toplam kayıt          : 1173
Tekrarlı text sayısı  : 62
Unique text sayısı    : 1111

API queue: 1111

   annotation_id                                                                           text human_label
0    fiqa_000000                             Royal Mail chairman Donald Brydon set to step down    negative
1    fiqa_000001                                 Slump in Weir leads FTSE down from record high    negative
2    fiqa_000002                     AstraZeneca wins FDA approval for key new lung cancer pill    positive
3    fiqa_000003           UPDATE 1-Lloyds to cut 945 jobs as part of 3-year restructuring plan    negative
4    fiqa_000004               Standard Chartered Shifts Emerging-Markets Strategy After Losses    negative
5    fiqa_000005                      AstraZeneca's Lung Cancer Drug Tagrisso Gets FDA Approval    positive
6    fiqa_000006  Severn Trent share price rises as first half profit inches up as customer ...    positive
7    fiqa_000007             Glencore sees Tripoli-based NOC as sole legal seller of Libyan oil    positive
8    fiqa_000008            Lloyds to cut 945 jobs as part of three-year restructuring strategy    negative
9    fiqa_000009                                  AstraZeneca to Buy ZS Pharma for $2.7 Billion    positive
10   fiqa_000010                            Ackman, in email, says supports Valeant CEO Pearson    positive
11   fiqa_000011                       AstraZeneca sells US drug rights to Perrigo for $380 mln    positive
12   fiqa_000012            UPDATE 1-AstraZeneca buys ZS Pharma for $2.7 billion, pips Actelion    positive
13   fiqa_000013                                 CORRECTED-Shire to buy Dyax for about $5.9 bln    positive
14   fiqa_000014                  Barclays poised to replace Sir Mike Rake as he heads for exit    positive
15   fiqa_000015                            AstraZeneca Acquires ZS Pharma in $2.7 Billion Deal    positive
16   fiqa_000016                AstraZeneca shares climb 3% as drug maker ups profits forecasts    positive
17   fiqa_000017  Peroni and Grolsch put up for sale as AB InBev plans acquisition of SABMiller    positive
18   fiqa_000018                   easyJet expects resilient demand to withstand security fears    positive
19   fiqa_000019                                     Compass Group says positive for year ahead    positive

## 5. Ortak sentiment prompt'u

İki model de aynı talimatlarla değerlendirilir. Girdi sırası korunur.

In [8]:
PROMPT_TEMPLATE = r'''
You are an expert financial sentiment annotator.

Classify the OVERALL FINANCIAL SENTIMENT of every provided text.

You MUST assign exactly ONE label:

- positive
- negative
- neutral

LABEL DEFINITIONS

positive:
The text communicates an overall favorable financial or business
development, such as stronger performance, increased profits/revenue,
successful expansion, improving outlook, favorable market developments,
or beneficial investor/business implications.

negative:
The text communicates an overall unfavorable financial or business
development, such as falling profits/revenue, weaker performance,
deteriorating outlook, losses, business problems, significant risks,
failures, or adverse investor/business implications.

neutral:
The text is primarily factual, descriptive, procedural, or informational
and does not communicate a clearly favorable or unfavorable financial
implication.

RULES

1. Classify the meaning of the WHOLE text, not individual words.

2. Do not automatically classify words such as "up", "rise", "growth",
   "fall", "drop", or "weak". Consider the complete financial meaning.

3. Consider expectations and comparisons.
   "profit rises more than expected" -> positive
   "profit rises less than expected" -> negative
   "orders fall more than expected" -> negative

4. If both positive and negative information is present:
   - choose the dominant financial implication;
   - if genuinely balanced with no clear dominant direction, use neutral.

5. Never return "mixed".

6. Neutral does not mean uncertainty. Use neutral when the text itself is
   informational or balanced.

7. Do not use outside knowledge about companies or events.
   Classify only what can reasonably be inferred from the supplied text.

8. Preserve the input order.

OUTPUT FORMAT

Return JSON only:

{"labels": ["positive", "neutral", "negative"]}

The labels array MUST contain exactly one label for every input item.

Allowed labels:
positive
negative
neutral

INPUT TEXTS:
'''

def build_prompt(texts):
    parts = []

    for i, text in enumerate(texts, start=1):
        parts.append(
            f"TEXT {i}:\n{text}"
        )

    return (
        PROMPT_TEMPLATE
        + "\n\n"
        + "\n\n".join(parts)
    )

## 6. JSON parser ve retry yardımcıları

In [9]:
def normalize_label(value):
    value = str(value).strip().lower()

    if value not in VALID_LABELS:
        raise ValueError(
            f"Geçersiz label: {value!r}"
        )

    return value


def parse_labels_json(raw, expected_count):
    if not raw:
        raise RuntimeError(
            "Boş model cevabı."
        )

    try:
        data = json.loads(raw)
    except json.JSONDecodeError as e:
        raise RuntimeError(
            f"Geçerli JSON alınamadı: {raw!r}"
        ) from e

    labels = data.get("labels")

    if not isinstance(labels, list):
        raise RuntimeError(
            f"'labels' listesi bulunamadı: {data!r}"
        )

    if len(labels) != expected_count:
        raise RuntimeError(
            f"Beklenen {expected_count} label, "
            f"gelen {len(labels)}"
        )

    return [
        normalize_label(x)
        for x in labels
    ]


def extract_retry_delay(error):
    message = str(error)

    patterns = [
        r"retryDelay['\"]?\s*[:=]\s*['\"]?(\d+(?:\.\d+)?)s",
        r"retry in\s+(\d+(?:\.\d+)?)s",
    ]

    for pattern in patterns:
        match = re.search(
            pattern,
            message,
            flags=re.IGNORECASE
        )

        if match:
            return float(match.group(1))

    return None


def retry_sleep(retry_no, error, provider):
    base = min(
        5 * (2 ** (retry_no - 1)),
        120
    )

    suggested = extract_retry_delay(error)

    wait_seconds = max(
        base,
        suggested if suggested is not None else 0
    )

    print(
        f"⚠️ {provider} hata | "
        f"Retry #{retry_no} | "
        f"{wait_seconds:.1f}s bekleme"
    )

    print(
        "   ",
        str(error)[:500]
    )

    time.sleep(wait_seconds)

## 7. ChatGPT batch

In [10]:
def ask_chatgpt_batch(texts):
    prompt = build_prompt(texts)

    for retry_no in range(
        1,
        MAX_RETRIES + 1
    ):
        try:
            response = openai_client.responses.create(
                model=OPENAI_MODEL,
                input=prompt,
                text={
                    "format": {
                        "type": "json_schema",
                        "name": "financial_sentiment_labels",
                        "strict": True,
                        "schema": {
                            "type": "object",
                            "properties": {
                                "labels": {
                                    "type": "array",
                                    "items": {
                                        "type": "string",
                                        "enum": VALID_LABELS,
                                    },
                                }
                            },
                            "required": ["labels"],
                            "additionalProperties": False,
                        },
                    }
                },
            )

            return parse_labels_json(
                response.output_text,
                expected_count=len(texts),
            )

        except KeyboardInterrupt:
            raise

        except Exception as e:

            if retry_no >= MAX_RETRIES:
                raise RuntimeError(
                    f"ChatGPT batch "
                    f"{MAX_RETRIES} retry sonrası başarısız."
                ) from e

            retry_sleep(
                retry_no,
                e,
                "ChatGPT",
            )

## 8. Gemini batch

In [11]:
def ask_gemini_batch(texts):
    prompt = build_prompt(texts)

    for retry_no in range(
        1,
        MAX_RETRIES + 1
    ):
        try:
            response = gemini_client.models.generate_content(
                model=GEMINI_MODEL,
                contents=prompt,
                config=types.GenerateContentConfig(
                    temperature=0.0,
                    response_mime_type="application/json",
                ),
            )

            raw = getattr(
                response,
                "text",
                None
            )

            return parse_labels_json(
                raw,
                expected_count=len(texts),
            )

        except KeyboardInterrupt:
            raise

        except Exception as e:

            if retry_no >= MAX_RETRIES:
                raise RuntimeError(
                    f"Gemini batch "
                    f"{MAX_RETRIES} retry sonrası başarısız."
                ) from e

            retry_sleep(
                retry_no,
                e,
                "Gemini",
            )

## 9. Önce API testi

Bu hücre başarılı olmadan 1.173 kaydın tamamını çalıştırma.

In [12]:
TEST_TEXTS = [
    "Revenue increased significantly and exceeded analyst expectations.",
    "The company reported a major decline in quarterly profit.",
    "The company will publish its quarterly results next week.",
]

print("=" * 100)
print("CHATGPT TEST")
print("=" * 100)

chatgpt_test = ask_chatgpt_batch(
    TEST_TEXTS
)

print("ChatGPT:", chatgpt_test)

print("\n" + "=" * 100)
print("GEMINI TEST")
print("=" * 100)

gemini_test = ask_gemini_batch(
    TEST_TEXTS
)

print("Gemini:", gemini_test)

assert len(chatgpt_test) == len(TEST_TEXTS)
assert len(gemini_test) == len(TEST_TEXTS)

print("\n✅ İki API de başarılı.")

====================================================================================================
CHATGPT TEST
====================================================================================================

Direct use of automatic function calling (AFC) in Models.generate_content is not recommended. Instead, we recommend to use AFC in Chat.send_message. Similarly, direct use of AFC in Models.generate_content_stream is not recommended. Instead, we recommend to use AFC in Chat.send_message_stream.

ChatGPT: ['positive', 'negative', 'neutral']

====================================================================================================
GEMINI TEST
====================================================================================================
Gemini: ['positive', 'negative', 'neutral']

✅ İki API de başarılı.

## 10. Checkpoint yardımcıları

Her başarılı batch anında ilgili provider'ın checkpoint dosyasına append edilir.

In [13]:
def checkpoint_path(provider):
    return (
        CHECKPOINT_DIR
        / f"fiqa_{provider}_checkpoint.csv"
    )


CHECKPOINT_COLUMNS = [
    "annotation_id",
    "text_key",
    "text",
    "label",
]


def load_checkpoint(path):
    path = Path(path)

    if (
        not path.exists()
        or path.stat().st_size == 0
    ):
        return pd.DataFrame(
            columns=CHECKPOINT_COLUMNS
        )

    try:
        df = pd.read_csv(
            path,
            encoding="utf-8-sig",
            dtype=str,
        )

    except pd.errors.EmptyDataError:
        return pd.DataFrame(
            columns=CHECKPOINT_COLUMNS
        )

    missing = (
        set(CHECKPOINT_COLUMNS)
        - set(df.columns)
    )

    if missing:
        raise ValueError(
            f"Checkpoint kolonları eksik: {missing}"
        )

    df["label"] = (
        df["label"]
        .astype("string")
        .str.strip()
        .str.lower()
    )

    df = df[
        df["label"].isin(VALID_LABELS)
    ].copy()

    return (
        df.drop_duplicates(
            subset=["annotation_id"],
            keep="last",
        )
        .reset_index(drop=True)
    )


def append_checkpoint(path, rows):
    path = Path(path)

    batch_df = pd.DataFrame(rows)

    if batch_df.empty:
        return

    write_header = (
        not path.exists()
        or path.stat().st_size == 0
    )

    batch_df.to_csv(
        path,
        mode="a",
        header=write_header,
        index=False,
        encoding="utf-8-sig",
    )


def checkpoint_label_map(path):
    ckpt = load_checkpoint(path)

    if ckpt.empty:
        return {}

    return (
        ckpt
        .drop_duplicates(
            subset=["annotation_id"],
            keep="last",
        )
        .set_index("annotation_id")["label"]
        .to_dict()
    )

## 11. Genel checkpoint/resume labeling fonksiyonu

In [14]:
def run_labeling(
    queue_df,
    provider,
    label_func,
    interval_seconds,
):
    queue_df = queue_df.copy()

    checkpoint_file = checkpoint_path(
        provider
    )

    existing = checkpoint_label_map(
        checkpoint_file
    )

    label_column = f"{provider}_label"

    queue_df[label_column] = (
        queue_df["annotation_id"]
        .map(existing)
        .astype("string")
    )

    valid_existing = (
        queue_df[label_column]
        .isin(VALID_LABELS)
    )

    remaining = queue_df.index[
        ~valid_existing
    ].tolist()

    total_batches = math.ceil(
        len(remaining) / BATCH_SIZE
    )

    print("\n" + "#" * 110)
    print(
        f"{provider.upper()} | FiQA"
    )
    print(
        f"Toplam unique kayıt : {len(queue_df):,}"
    )
    print(
        f"Checkpoint'ten hazır: {valid_existing.sum():,}"
    )
    print(
        f"İşlenecek           : {len(remaining):,}"
    )
    print(
        f"Batch                : {total_batches:,}"
    )
    print(
        f"Batch size           : {BATCH_SIZE}"
    )
    print(
        f"Checkpoint           : {checkpoint_file}"
    )
    print("#" * 110)

    if not remaining:
        print("✅ Bu provider için bütün kayıtlar checkpoint'te mevcut.")
        return queue_df

    last_call = 0.0

    for batch_no, start in enumerate(
        range(
            0,
            len(remaining),
            BATCH_SIZE,
        ),
        start=1,
    ):

        batch_indices = remaining[
            start:start + BATCH_SIZE
        ]

        texts = [
            str(
                queue_df.loc[idx, "text"]
            )
            for idx in batch_indices
        ]

        elapsed = (
            time.time()
            - last_call
        )

        if elapsed < interval_seconds:
            time.sleep(
                interval_seconds - elapsed
            )

        print(
            f"[{batch_no}/{total_batches}] "
            f"{provider} | "
            f"{len(batch_indices)} kayıt"
        )

        labels = label_func(texts)

        if len(labels) != len(batch_indices):
            raise RuntimeError(
                f"{provider} batch {batch_no}: "
                f"beklenen {len(batch_indices)} label, "
                f"gelen {len(labels)}"
            )

        last_call = time.time()

        checkpoint_rows = []

        for idx, label in zip(
            batch_indices,
            labels,
        ):
            annotation_id = str(
                queue_df.loc[
                    idx,
                    "annotation_id",
                ]
            )

            text_key = str(
                queue_df.loc[
                    idx,
                    "text_key",
                ]
            )

            text = str(
                queue_df.loc[
                    idx,
                    "text",
                ]
            )

            queue_df.loc[
                idx,
                label_column,
            ] = label

            checkpoint_rows.append({
                "annotation_id": annotation_id,
                "text_key": text_key,
                "text": text,
                "label": label,
            })

        append_checkpoint(
            checkpoint_file,
            checkpoint_rows,
        )

        print(
            f"  ✅ checkpoint yazıldı: "
            f"{len(checkpoint_rows)}"
        )

    return queue_df

## 12. ChatGPT ile FiQA'nın tamamını etiketle

Notebook kesilirse aynı hücreyi tekrar çalıştırabilirsin; checkpoint'teki kayıtlar atlanır.

In [15]:
fiqa_chatgpt = run_labeling(
    queue_df=fiqa_queue,
    provider="chatgpt",
    label_func=ask_chatgpt_batch,
    interval_seconds=OPENAI_REQUEST_INTERVAL,
)

print("\n✅ FiQA ChatGPT annotation tamamlandı.")

##############################################################################################################
CHATGPT | FiQA
Toplam unique kayıt : 1,111
Checkpoint'ten hazır: 0
İşlenecek           : 1,111
Batch                : 223
Batch size           : 5
Checkpoint           : D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\annotations\reannotation_22_fiqa\checkpoints\fiqa_chatgpt_checkpoint.csv
##############################################################################################################
[1/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[2/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[3/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[4/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[5/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[6/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[7/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[8/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[9/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[10/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[11/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[12/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[13/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[14/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[15/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[16/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[17/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[18/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[19/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[20/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[21/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[22/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[23/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[24/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[25/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[26/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[27/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[28/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[29/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[30/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[31/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[32/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[33/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[34/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[35/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[36/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[37/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[38/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[39/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[40/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[41/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[42/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[43/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[44/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[45/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[46/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[47/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[48/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[49/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[50/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[51/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[52/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[53/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[54/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[55/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[56/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[57/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[58/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[59/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[60/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[61/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[62/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[63/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[64/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[65/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[66/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[67/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[68/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[69/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[70/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[71/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[72/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[73/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[74/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[75/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[76/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[77/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[78/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[79/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[80/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[81/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[82/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[83/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[84/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[85/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[86/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[87/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[88/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[89/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[90/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[91/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[92/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[93/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[94/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[95/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[96/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[97/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[98/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[99/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[100/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[101/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[102/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[103/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[104/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[105/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[106/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[107/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[108/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[109/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[110/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[111/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[112/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[113/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[114/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[115/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[116/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[117/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[118/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[119/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[120/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[121/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[122/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[123/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[124/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[125/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[126/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[127/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[128/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[129/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[130/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[131/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[132/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[133/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[134/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[135/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[136/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[137/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[138/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[139/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[140/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[141/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[142/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[143/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[144/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[145/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[146/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[147/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[148/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[149/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[150/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[151/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[152/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[153/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[154/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[155/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[156/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[157/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[158/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[159/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[160/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[161/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[162/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[163/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[164/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[165/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[166/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[167/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[168/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[169/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[170/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[171/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[172/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[173/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[174/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[175/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[176/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[177/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[178/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[179/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[180/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[181/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[182/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[183/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[184/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[185/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[186/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[187/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[188/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[189/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[190/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[191/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[192/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[193/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[194/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[195/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[196/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[197/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[198/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[199/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[200/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[201/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[202/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[203/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[204/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[205/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[206/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[207/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[208/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[209/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[210/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[211/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[212/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[213/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[214/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[215/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[216/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[217/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[218/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[219/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[220/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[221/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[222/223] chatgpt | 5 kayıt
  ✅ checkpoint yazıldı: 5
[223/223] chatgpt | 1 kayıt
  ✅ checkpoint yazıldı: 1

✅ FiQA ChatGPT annotation tamamlandı.

## 13. Gemini ile FiQA'nın tamamını etiketle

ChatGPT bittikten sonra Gemini çalışır. Gemini'nin checkpoint'i ChatGPT'den ayrıdır.

In [16]:
fiqa_gemini = run_labeling(
    queue_df=fiqa_chatgpt,
    provider="gemini",
    label_func=ask_gemini_batch,
    interval_seconds=GEMINI_REQUEST_INTERVAL,
)

print("\n✅ FiQA Gemini annotation tamamlandı.")

##############################################################################################################
GEMINI | FiQA
Toplam unique kayıt : 1,111
Checkpoint'ten hazır: 0
İşlenecek           : 1,111
Batch                : 223
Batch size           : 5
Checkpoint           : D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\annotations\reannotation_22_fiqa\checkpoints\fiqa_gemini_checkpoint.csv
##############################################################################################################
[1/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[2/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[3/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[4/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[5/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[6/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[7/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[8/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[9/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[10/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[11/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[12/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[13/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[14/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[15/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[16/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[17/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[18/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[19/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[20/223] gemini | 5 kayıt
⚠️ Gemini hata | Retry #1 | 5.0s bekleme
    Geçersiz label: 'mixed'
⚠️ Gemini hata | Retry #2 | 10.0s bekleme
    Geçersiz label: 'mixed'
⚠️ Gemini hata | Retry #3 | 20.0s bekleme
    Geçersiz label: 'mixed'
  ✅ checkpoint yazıldı: 5
[21/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[22/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[23/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[24/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[25/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[26/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[27/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[28/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[29/223] gemini | 5 kayıt
⚠️ Gemini hata | Retry #1 | 5.0s bekleme
    Geçersiz label: 'mixed'
  ✅ checkpoint yazıldı: 5
[30/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[31/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[32/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[33/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[34/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[35/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[36/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[37/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[38/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[39/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[40/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[41/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[42/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[43/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[44/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[45/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[46/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[47/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[48/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[49/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[50/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[51/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[52/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[53/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[54/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[55/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[56/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[57/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[58/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[59/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[60/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[61/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[62/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[63/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[64/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[65/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[66/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[67/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[68/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[69/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[70/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[71/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[72/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[73/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[74/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[75/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[76/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[77/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[78/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[79/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[80/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[81/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[82/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[83/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[84/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[85/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[86/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[87/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[88/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[89/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[90/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[91/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[92/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[93/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[94/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[95/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[96/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[97/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[98/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[99/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[100/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[101/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[102/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[103/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[104/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[105/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[106/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[107/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[108/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[109/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[110/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[111/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[112/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[113/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[114/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[115/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[116/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[117/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[118/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[119/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[120/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[121/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[122/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[123/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[124/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[125/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[126/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[127/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[128/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[129/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[130/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[131/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[132/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[133/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[134/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[135/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[136/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[137/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[138/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[139/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[140/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[141/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[142/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[143/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[144/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[145/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[146/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[147/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[148/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[149/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[150/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[151/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[152/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[153/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[154/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[155/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[156/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[157/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[158/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[159/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[160/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[161/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[162/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[163/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[164/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[165/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[166/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[167/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[168/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[169/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[170/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[171/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[172/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[173/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[174/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[175/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[176/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[177/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[178/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[179/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[180/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[181/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[182/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[183/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[184/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[185/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[186/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[187/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[188/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[189/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[190/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[191/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[192/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[193/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[194/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[195/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[196/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[197/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[198/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[199/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[200/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[201/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[202/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[203/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[204/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[205/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[206/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[207/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[208/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[209/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[210/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[211/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[212/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[213/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[214/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[215/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[216/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[217/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[218/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[219/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[220/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[221/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[222/223] gemini | 5 kayıt
  ✅ checkpoint yazıldı: 5
[223/223] gemini | 1 kayıt
  ✅ checkpoint yazıldı: 1

✅ FiQA Gemini annotation tamamlandı.

## 14. Final sonuç tablosu

In [17]:
fiqa_final = fiqa_gemini.copy()

fiqa_final["chatgpt_label"] = (
    fiqa_final["chatgpt_label"]
    .astype("string")
)

fiqa_final["gemini_label"] = (
    fiqa_final["gemini_label"]
    .astype("string")
)

fiqa_final["llm_agreement"] = (
    fiqa_final["chatgpt_label"]
    == fiqa_final["gemini_label"]
)

fiqa_final["human_chatgpt_agreement"] = (
    fiqa_final["human_label"]
    == fiqa_final["chatgpt_label"]
)

fiqa_final["human_gemini_agreement"] = (
    fiqa_final["human_label"]
    == fiqa_final["gemini_label"]
)

print("=" * 110)
print("FiQA FINAL")
print("=" * 110)

print("Toplam kayıt:", len(fiqa_final))

print("\nEksiksiz ChatGPT:",
      fiqa_final["chatgpt_label"].isin(VALID_LABELS).sum())

print("Eksiksiz Gemini :",
      fiqa_final["gemini_label"].isin(VALID_LABELS).sum())

print(
    "ChatGPT ↔ Gemini agreement:",
    fiqa_final["llm_agreement"].mean()
)

display(
    fiqa_final[
        [
            "text",
            "score",
            "human_label",
            "chatgpt_label",
            "gemini_label",
            "llm_agreement",
        ]
    ].head(50)
)

==============================================================================================================
FiQA FINAL
==============================================================================================================
Toplam kayıt: 1111

Eksiksiz ChatGPT: 1111
Eksiksiz Gemini : 1111
ChatGPT ↔ Gemini agreement: 0.8541854185418541

                                                                                  text  score human_label chatgpt_label gemini_label llm_agreement
0                                   Royal Mail chairman Donald Brydon set to step down -0.374    negative       neutral      neutral          True
1                                       Slump in Weir leads FTSE down from record high -0.827    negative      negative     negative          True
2                           AstraZeneca wins FDA approval for key new lung cancer pill  0.549    positive      positive     positive          True
3                 UPDATE 1-Lloyds to cut 945 jobs as part of 3-year restructuring plan -0.266    negative      negative     negative          True
4                     Standard Chartered Shifts Emerging-Markets Strategy After Losses -0.461    negative      negative     negative          True
5                            AstraZeneca's Lung Cancer Drug Tagrisso Gets FDA Approval  0.393    positive      positive     positive          True
6        Severn Trent share price rises as first half profit inches up as customer ...  0.526    positive      positive     positive          True
7                   Glencore sees Tripoli-based NOC as sole legal seller of Libyan oil  0.037    positive       neutral      neutral          True
8                  Lloyds to cut 945 jobs as part of three-year restructuring strategy -0.532    negative      negative     negative          True
9                                        AstraZeneca to Buy ZS Pharma for $2.7 Billion  0.593    positive       neutral      neutral          True
10                                 Ackman, in email, says supports Valeant CEO Pearson  0.166    positive      positive      neutral         False
11                            AstraZeneca sells US drug rights to Perrigo for $380 mln  0.326    positive       neutral      neutral          True
12                 UPDATE 1-AstraZeneca buys ZS Pharma for $2.7 billion, pips Actelion  0.468    positive      positive     positive          True
13                                      CORRECTED-Shire to buy Dyax for about $5.9 bln  0.402    positive       neutral      neutral          True
14                       Barclays poised to replace Sir Mike Rake as he heads for exit  0.077    positive       neutral      neutral          True
15                                 AstraZeneca Acquires ZS Pharma in $2.7 Billion Deal  0.520    positive       neutral      neutral          True
16                     AstraZeneca shares climb 3% as drug maker ups profits forecasts  0.640    positive      positive     positive          True
17       Peroni and Grolsch put up for sale as AB InBev plans acquisition of SABMiller  0.551    positive       neutral      neutral          True
18                        easyJet expects resilient demand to withstand security fears  0.165    positive      positive     positive          True
19                                          Compass Group says positive for year ahead  0.634    positive      positive     positive          True
20                Bunzl Lifts Dividend Again As Acquisitions Continue To Boost Profits  0.401    positive      positive     positive          True
21                                       US dollar wipes out sales gains for SABMiller -0.582    negative      negative     negative          True
22         UPDATE 1-SABMiller 2nd-quarter underlying sales rise, forex impacts margins  0.043    positive       neutral      neutral          True
23                   UPDATE 2-Pricey beers lift SABMiller's quarterly underlying sales  0.429    positive      positive     positive          True
24                      Valeant CEO Pledges to Heed Critics After `Painful' Experience -0.381    negative      negative      neutral         False
25   Are Aviva plc, Direct Line Insurance Group PLC And Admiral Group plc Set To Soar?  0.324    positive       neutral      neutral          True
27                          StanChart and RBS struggle in Bank of England stress tests -0.738    negative      negative     negative          True
29                 REFILE-UPDATE 4-Britain's Lloyds to pay first dividend since rescue  0.522    positive      positive     positive          True
30                                  Barclays sells benchmark indices unit to Bloomberg  0.281    positive       neutral      neutral          True
31  Sainsbury's, Asda, Tesco and Morrisons will all cut petrol prices as oil falls ... -0.251    negative       neutral      neutral          True
34                    EU drops Shell, BP, Statoil from ethanol benchmark investigation  0.276    positive      positive      neutral         False
36                     AstraZeneca Explores Potential Deal With Acerta for Cancer Drug  0.372    positive       neutral      neutral          True
37                         Shell and BG Shareholders to Vote on Deal at End of January  0.000     neutral       neutral      neutral          True
38                         AstraZeneca chases Acerta to secure next cancer drug winner  0.519    positive      positive     positive          True
39                              CompaniesTesco off to a bad start over Xmas â€“ Kantar -0.604    negative      negative     negative          True
40      DBS, Julius Baer emerge as potential bidders for Barclays Asia wealth unit ...  0.310    positive       neutral      neutral          True
41                 Why AstraZeneca plc & Dixons Carphone PLC Are Red-Hot Growth Stars!  0.766    positive      positive     positive          True
42                                 BBCN Bancorp to buy Wilshire Bancorp in $1 bln deal  0.818    positive       neutral     positive         False
43   ITV share price jumps on report of Comcast's NBCUniversal bidding to takeover ...  0.611    positive      positive     positive          True
45                     Glencore Studies Possible IPO for Agricultural Trading Business  0.408    positive       neutral      neutral          True
46                                   Can Christmas Save Sainsbury's plc And Tesco plc? -0.175    negative      negative      neutral         False
47              UPDATE 1-AstraZeneca boosts respiratory unit with $575 mln Takeda deal  0.470    positive      positive     positive          True
48                      Bilfinger Industrial Services win Â£100m BP contract extension  0.113    positive      positive     positive          True
49                       Standard Chartered, RBS Escape Capital Raising in Stress Test  0.335    positive      positive     positive          True
51                      AstraZeneca weighing up Acerta bid to secure blood cancer drug  0.284    positive       neutral      neutral          True
52           GlaxoSmithKline set to complete $20 billion Novartis asset swap next week  0.189    positive       neutral      neutral          True
53              2 Turnaround Buys For 2016? BHP Billiton plc And Home Retail Group Plc  0.492    positive      positive     positive          True
54            L&G completes UK's largest medically underwritten bulk pension risk deal  0.250    positive      positive     positive          True
55                   Meggitt share price tumbles as profit falls in 'challenging year' -0.854    negative      negative     negative          True
56                Drugmaker Shire to buy Baxalta for $32 billion after 6-month pursuit  0.437    positive      positive      neutral         False

## 15. Cohen's Kappa

Üç karşılaştırma yapılır:
- Human ↔ ChatGPT
- Human ↔ Gemini
- ChatGPT ↔ Gemini

In [18]:
PAIR_DEFS = [
    (
        "human_label",
        "chatgpt_label",
        "Human vs ChatGPT",
    ),
    (
        "human_label",
        "gemini_label",
        "Human vs Gemini",
    ),
    (
        "chatgpt_label",
        "gemini_label",
        "ChatGPT vs Gemini",
    ),
]


def pairwise_kappa(
    df,
    col_a,
    col_b,
):
    data = df[
        df[col_a].isin(VALID_LABELS)
        & df[col_b].isin(VALID_LABELS)
    ].copy()

    if data.empty:
        return {
            "n": 0,
            "agreement": np.nan,
            "kappa": np.nan,
        }

    agreement = (
        data[col_a]
        == data[col_b]
    ).mean()

    kappa = cohen_kappa_score(
        data[col_a],
        data[col_b],
        labels=VALID_LABELS,
    )

    return {
        "n": len(data),
        "agreement": agreement,
        "kappa": kappa,
    }


kappa_rows = []

for col_a, col_b, name in PAIR_DEFS:

    result = pairwise_kappa(
        fiqa_final,
        col_a,
        col_b,
    )

    row = {
        "dataset": "FiQA",
        "comparison": name,
        "n": result["n"],
        "agreement": result["agreement"],
        "kappa": result["kappa"],
    }

    kappa_rows.append(row)

    print("\n" + "=" * 80)
    print(name)
    print("=" * 80)
    print("N        :", result["n"])

    if pd.notna(result["agreement"]):
        print(
            "Agreement:",
            f"{result['agreement']:.4f}",
        )

    if pd.notna(result["kappa"]):
        print(
            "Cohen κ :",
            f"{result['kappa']:.4f}",
        )

kappa_df = pd.DataFrame(kappa_rows)

display(kappa_df)

================================================================================
Human vs ChatGPT
================================================================================
N        : 1111
Agreement: 0.7786
Cohen κ : 0.6089

================================================================================
Human vs Gemini
================================================================================
N        : 1111
Agreement: 0.6985
Cohen κ : 0.5094

================================================================================
ChatGPT vs Gemini
================================================================================
N        : 1111
Agreement: 0.8542
Cohen κ : 0.7718

  dataset         comparison     n  agreement     kappa
0    FiQA   Human vs ChatGPT  1111   0.778578  0.608909
1    FiQA    Human vs Gemini  1111   0.698470  0.509441
2    FiQA  ChatGPT vs Gemini  1111   0.854185  0.771791

## 16. Sonuçları diske yaz

In [19]:
checkpoint_chatgpt = checkpoint_path("chatgpt")
checkpoint_gemini = checkpoint_path("gemini")

final_path = (
    FINAL_DIR
    / "fiqa_reannotated_chatgpt_gemini.csv"
)

kappa_path = (
    RESULT_DIR
    / "fiqa_kappa_results.csv"
)

fiqa_final.to_csv(
    final_path,
    index=False,
    encoding="utf-8-sig",
)

kappa_df.to_csv(
    kappa_path,
    index=False,
    encoding="utf-8-sig",
)

print("✅ ChatGPT checkpoint:", checkpoint_chatgpt)
print("✅ Gemini checkpoint :", checkpoint_gemini)
print("✅ Final CSV          :", final_path)
print("✅ Kappa sonuçları    :", kappa_path)

✅ ChatGPT checkpoint: D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\annotations\reannotation_22_fiqa\checkpoints\fiqa_chatgpt_checkpoint.csv
✅ Gemini checkpoint : D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\annotations\reannotation_22_fiqa\checkpoints\fiqa_gemini_checkpoint.csv
✅ Final CSV          : D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\annotations\reannotation_22_fiqa\final\fiqa_reannotated_chatgpt_gemini.csv
✅ Kappa sonuçları    : D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\annotations\reannotation_22_fiqa\results\fiqa_kappa_results.csv

## 17. Eğitim için kullanılabilecek temiz çıktı

Bu dosya **FiQA'nın orijinal `human_label`ını** ve iki LLM etiketini birlikte saklar.

`llm_agreement == True` filtresi uygulanırsa yalnızca ChatGPT ve Gemini'nin aynı etikette olduğu kayıtlar seçilebilir. Bu notebook otomatik olarak kayıtları silmez; hem tam sonucu hem de agreement bilgisini korur.

In [20]:
fiqa_training_candidates = fiqa_final[
    fiqa_final["llm_agreement"]
    & fiqa_final["chatgpt_label"].isin(VALID_LABELS)
].copy()

fiqa_training_candidates["label"] = (
    fiqa_training_candidates["chatgpt_label"]
)

training_path = (
    FINAL_DIR
    / "fiqa_training_candidates_llm_agreement.csv"
)

fiqa_training_candidates[
    [
        "text",
        "label",
        "human_label",
        "chatgpt_label",
        "gemini_label",
        "score",
        "dataset",
    ]
].to_csv(
    training_path,
    index=False,
    encoding="utf-8-sig",
)

print(
    "Agreement olan eğitim adayı:",
    len(fiqa_training_candidates)
)

print(
    "Dosya:",
    training_path
)

display(
    fiqa_training_candidates[
        [
            "text",
            "label",
            "human_label",
            "chatgpt_label",
            "gemini_label",
        ]
    ].head(30)
)

Agreement olan eğitim adayı: 949
Dosya: D:\serkan.kaymak\financial_sentiment_thesis\financial_sentiment_thesis\db\annotations\reannotation_22_fiqa\final\fiqa_training_candidates_llm_agreement.csv

                                                                                  text     label human_label chatgpt_label gemini_label
0                                   Royal Mail chairman Donald Brydon set to step down   neutral    negative       neutral      neutral
1                                       Slump in Weir leads FTSE down from record high  negative    negative      negative     negative
2                           AstraZeneca wins FDA approval for key new lung cancer pill  positive    positive      positive     positive
3                 UPDATE 1-Lloyds to cut 945 jobs as part of 3-year restructuring plan  negative    negative      negative     negative
4                     Standard Chartered Shifts Emerging-Markets Strategy After Losses  negative    negative      negative     negative
5                            AstraZeneca's Lung Cancer Drug Tagrisso Gets FDA Approval  positive    positive      positive     positive
6        Severn Trent share price rises as first half profit inches up as customer ...  positive    positive      positive     positive
7                   Glencore sees Tripoli-based NOC as sole legal seller of Libyan oil   neutral    positive       neutral      neutral
8                  Lloyds to cut 945 jobs as part of three-year restructuring strategy  negative    negative      negative     negative
9                                        AstraZeneca to Buy ZS Pharma for $2.7 Billion   neutral    positive       neutral      neutral
11                            AstraZeneca sells US drug rights to Perrigo for $380 mln   neutral    positive       neutral      neutral
12                 UPDATE 1-AstraZeneca buys ZS Pharma for $2.7 billion, pips Actelion  positive    positive      positive     positive
13                                      CORRECTED-Shire to buy Dyax for about $5.9 bln   neutral    positive       neutral      neutral
14                       Barclays poised to replace Sir Mike Rake as he heads for exit   neutral    positive       neutral      neutral
15                                 AstraZeneca Acquires ZS Pharma in $2.7 Billion Deal   neutral    positive       neutral      neutral
16                     AstraZeneca shares climb 3% as drug maker ups profits forecasts  positive    positive      positive     positive
17       Peroni and Grolsch put up for sale as AB InBev plans acquisition of SABMiller   neutral    positive       neutral      neutral
18                        easyJet expects resilient demand to withstand security fears  positive    positive      positive     positive
19                                          Compass Group says positive for year ahead  positive    positive      positive     positive
20                Bunzl Lifts Dividend Again As Acquisitions Continue To Boost Profits  positive    positive      positive     positive
21                                       US dollar wipes out sales gains for SABMiller  negative    negative      negative     negative
22         UPDATE 1-SABMiller 2nd-quarter underlying sales rise, forex impacts margins   neutral    positive       neutral      neutral
23                   UPDATE 2-Pricey beers lift SABMiller's quarterly underlying sales  positive    positive      positive     positive
25   Are Aviva plc, Direct Line Insurance Group PLC And Admiral Group plc Set To Soar?   neutral    positive       neutral      neutral
27                          StanChart and RBS struggle in Bank of England stress tests  negative    negative      negative     negative
29                 REFILE-UPDATE 4-Britain's Lloyds to pay first dividend since rescue  positive    positive      positive     positive
30                                  Barclays sells benchmark indices unit to Bloomberg   neutral    positive       neutral      neutral
31  Sainsbury's, Asda, Tesco and Morrisons will all cut petrol prices as oil falls ...   neutral    negative       neutral      neutral
36                     AstraZeneca Explores Potential Deal With Acerta for Cancer Drug   neutral    positive       neutral      neutral
37                         Shell and BG Shareholders to Vote on Deal at End of January   neutral     neutral       neutral      neutral